from ortools.sat.python import cp_model

model = cp_model.CpModel()
wmma_m = model.NewIntVar(8, 32, 'wmma_m')
wmma_m_cand0 = model.NewIntVar(0, 1, 'wmma_m_cand0')
wmma_m_cand1 = model.NewIntVar(0, 1, 'wmma_m_cand1')
wmma_m_cand2 = model.NewIntVar(0, 1, 'wmma_m_cand2')
wmma_k = model.NewIntVar(16, 16, 'wmma_k')
wmma_n = model.NewIntVar(8, 32, 'wmma_n')
wmma_n_cand0 = model.NewIntVar(0, 1, 'wmma_n_cand0')
wmma_n_cand1 = model.NewIntVar(0, 1, 'wmma_n_cand1')
wmma_n_cand2 = model.NewIntVar(0, 1, 'wmma_n_cand2')
wmma_m_wmma_n = model.NewIntVar(1, 4096, 'wmma_m_wmma_n')
out_wmma_accumulator_shared_pos = model.NewIntVar(0, 3, 'out_wmma_accumulator_shared_pos')
out_wmma_accumulator_local_pos = model.NewIntVar(0, 3, 'out_wmma_accumulator_local_pos')
out_shared_pos = model.NewIntVar(1, 5, 'out_shared_pos')
out_wmma_accumulator_shared_local_pos = model.NewIntVar(0, 1, 'out_wmma_accumulator_shared_local_pos')
out_unroll_pragma = model.NewIntVar(0, 5, 'out_unroll_pragma')
out_nn_outer = model.NewIntVar(1, 16, 'out_nn_outer')
out_nn_inner = model.NewIntVar(1, 16, 'out_nn_inner')
out_yy_outer = model.NewIntVar(1, 14, 'out_yy_outer')
out_yy_inner = model.NewIntVar(1, 14, 'out_yy_inner')
out_xx_outer = model.NewIntVar(1, 14, 'out_xx_outer')
out_xx_inner = model.NewIntVar(1, 14, 'out_xx_inner')
out_ff_outer = model.NewIntVar(1, 256, 'out_ff_outer')
out_ff_inner = model.NewIntVar(1, 256, 'out_ff_inner')
outnn_innertileSpatial = model.NewIntVar(1, 16, 'outnn_innertileSpatial')
out_nn_inner_outer = model.NewIntVar(1, 16, 'out_nn_inner_outer')
out_nn_inner_inner = model.NewIntVar(1, 16, 'out_nn_inner_inner')
outyy_innertileSpatial = model.NewIntVar(14, 14, 'outyy_innertileSpatial')
out_yy_inner_outer = model.NewIntVar(1, 14, 'out_yy_inner_outer')
out_yy_inner_inner = model.NewIntVar(1, 14, 'out_yy_inner_inner')
outxx_innertileSpatial = model.NewIntVar(14, 14, 'outxx_innertileSpatial')
out_xx_inner_outer = model.NewIntVar(1, 14, 'out_xx_inner_outer')
out_xx_inner_inner = model.NewIntVar(1, 14, 'out_xx_inner_inner')
outff_innertileSpatial = model.NewIntVar(1, 256, 'outff_innertileSpatial')
out_ff_inner_outer = model.NewIntVar(1, 256, 'out_ff_inner_outer')
out_ff_inner_inner = model.NewIntVar(1, 256, 'out_ff_inner_inner')
blockIdx_x = model.NewIntVar(1, 8888888, 'blockIdx_x')
outnn_innertileSpatial_outyy_innertileSpatial = model.NewIntVar(1, 8888888, 'outnn_innertileSpatial_outyy_innertileSpatial')
outnn_innertileSpatial_outyy_innertileSpatial_outxx_innertileSpatial = model.NewIntVar(1, 8888888, 'outnn_innertileSpatial_outyy_innertileSpatial_outxx_innertileSpatial')
out_nn_inner_outer_yy_inner_outer_fused_xx_inner_outer_fused_ff_inner_outer_fused = model.NewIntVar(1, 1000000, 'out_nn_inner_outer_yy_inner_outer_fused_xx_inner_outer_fused_ff_inner_outer_fused')
out_nn_inner_outer_out_yy_inner_outer = model.NewIntVar(1, 1000000, 'out_nn_inner_outer_out_yy_inner_outer')
out_nn_inner_outer_out_yy_inner_outer_out_xx_inner_outer = model.NewIntVar(1, 1000000, 'out_nn_inner_outer_out_yy_inner_outer_out_xx_inner_outer')
outnn_inner_innertileSpatial = model.NewIntVar(1, 16, 'outnn_inner_innertileSpatial')
out_nn_inner_inner_outer = model.NewIntVar(1, 16, 'out_nn_inner_inner_outer')
out_nn_inner_inner_inner = model.NewIntVar(1, 16, 'out_nn_inner_inner_inner')
outyy_inner_innertileSpatial = model.NewIntVar(1, 14, 'outyy_inner_innertileSpatial')
out_yy_inner_inner_outer = model.NewIntVar(1, 14, 'out_yy_inner_inner_outer')
out_yy_inner_inner_inner = model.NewIntVar(1, 14, 'out_yy_inner_inner_inner')
outxx_inner_innertileSpatial = model.NewIntVar(1, 14, 'outxx_inner_innertileSpatial')
out_xx_inner_inner_outer = model.NewIntVar(1, 14, 'out_xx_inner_inner_outer')
out_xx_inner_inner_inner = model.NewIntVar(1, 14, 'out_xx_inner_inner_inner')
outff_inner_innertileSpatial = model.NewIntVar(1, 256, 'outff_inner_innertileSpatial')
out_ff_inner_inner_outer = model.NewIntVar(1, 256, 'out_ff_inner_inner_outer')
out_ff_inner_inner_inner = model.NewIntVar(1, 256, 'out_ff_inner_inner_inner')
threadIdx_y = model.NewIntVar(1, 1024, 'threadIdx_y')
outnn_inner_innertileSpatial_outyy_inner_innertileSpatial = model.NewIntVar(1, 1024, 'outnn_inner_innertileSpatial_outyy_inner_innertileSpatial')
outnn_inner_innertileSpatial_outyy_inner_innertileSpatial_outxx_inner_innertileSpatial = model.NewIntVar(1, 1024, 'outnn_inner_innertileSpatial_outyy_inner_innertileSpatial_outxx_inner_innertileSpatial')
out_nn_inner_inner_outer_yy_inner_inner_outer_fused_xx_inner_inner_outer_fused_ff_inner_inner_outer_fused = model.NewIntVar(1, 1000000, 'out_nn_inner_inner_outer_yy_inner_inner_outer_fused_xx_inner_inner_outer_fused_ff_inner_inner_outer_fused')
out_nn_inner_inner_outer_out_yy_inner_inner_outer = model.NewIntVar(1, 1000000, 'out_nn_inner_inner_outer_out_yy_inner_inner_outer')
out_nn_inner_inner_outer_out_yy_inner_inner_outer_out_xx_inner_inner_outer = model.NewIntVar(1, 1000000, 'out_nn_inner_inner_outer_out_yy_inner_inner_outer_out_xx_inner_inner_outer')
outnn_inner_inner_innertileSpatial = model.NewIntVar(1, 16, 'outnn_inner_inner_innertileSpatial')
out_nn_inner_inner_inner_outer = model.NewIntVar(1, 16, 'out_nn_inner_inner_inner_outer')
out_nn_inner_inner_inner_inner = model.NewIntVar(1, 16, 'out_nn_inner_inner_inner_inner')
outyy_inner_inner_innertileSpatial = model.NewIntVar(1, 14, 'outyy_inner_inner_innertileSpatial')
out_yy_inner_inner_inner_outer = model.NewIntVar(1, 14, 'out_yy_inner_inner_inner_outer')
out_yy_inner_inner_inner_inner = model.NewIntVar(1, 14, 'out_yy_inner_inner_inner_inner')
outxx_inner_inner_innertileSpatial = model.NewIntVar(1, 14, 'outxx_inner_inner_innertileSpatial')
out_xx_inner_inner_inner_outer = model.NewIntVar(1, 14, 'out_xx_inner_inner_inner_outer')
out_xx_inner_inner_inner_inner = model.NewIntVar(1, 14, 'out_xx_inner_inner_inner_inner')
outff_inner_inner_innertileSpatial = model.NewIntVar(1, 256, 'outff_inner_inner_innertileSpatial')
out_ff_inner_inner_inner_outer = model.NewIntVar(1, 256, 'out_ff_inner_inner_inner_outer')
out_ff_inner_inner_inner_inner = model.NewIntVar(1, 256, 'out_ff_inner_inner_inner_inner')
threadIdx_x = model.NewIntVar(32, 32, 'threadIdx_x')
outnn_inner_inner_innertileSpatial_outyy_inner_inner_innertileSpatial = model.NewIntVar(1, 1024, 'outnn_inner_inner_innertileSpatial_outyy_inner_inner_innertileSpatial')
outnn_inner_inner_innertileSpatial_outyy_inner_inner_innertileSpatial_outxx_inner_inner_innertileSpatial = model.NewIntVar(1, 1024, 'outnn_inner_inner_innertileSpatial_outyy_inner_inner_innertileSpatial_outxx_inner_inner_innertileSpatial')
out_nn_inner_inner_inner_outer_yy_inner_inner_inner_outer_fused_xx_inner_inner_inner_outer_fused_ff_inner_inner_inner_outer_fused = model.NewIntVar(1, 1000000, 'out_nn_inner_inner_inner_outer_yy_inner_inner_inner_outer_fused_xx_inner_inner_inner_outer_fused_ff_inner_inner_inner_outer_fused')
out_nn_inner_inner_inner_outer_out_yy_inner_inner_inner_outer = model.NewIntVar(1, 1000000, 'out_nn_inner_inner_inner_outer_out_yy_inner_inner_inner_outer')
out_nn_inner_inner_inner_outer_out_yy_inner_inner_inner_outer_out_xx_inner_inner_inner_outer = model.NewIntVar(1, 1000000, 'out_nn_inner_inner_inner_outer_out_yy_inner_inner_inner_outer_out_xx_inner_inner_inner_outer')
out_vectorize = model.NewIntVar(1, 8, 'out_vectorize')
out_vectorize_cand0 = model.NewIntVar(0, 1, 'out_vectorize_cand0')
out_vectorize_cand1 = model.NewIntVar(0, 1, 'out_vectorize_cand1')
out_vectorize_cand2 = model.NewIntVar(0, 1, 'out_vectorize_cand2')
out_vectorize_cand3 = model.NewIntVar(0, 1, 'out_vectorize_cand3')
outnn_inner_inner_inner_innertileSpatial = model.NewIntVar(1, 16, 'outnn_inner_inner_inner_innertileSpatial')
out_nn_inner_inner_inner_inner_outer = model.NewIntVar(1, 16, 'out_nn_inner_inner_inner_inner_outer')
out_nn_inner_inner_inner_inner_inner = model.NewIntVar(1, 16, 'out_nn_inner_inner_inner_inner_inner')
outyy_inner_inner_inner_innertileSpatial = model.NewIntVar(1, 14, 'outyy_inner_inner_inner_innertileSpatial')
out_yy_inner_inner_inner_inner_outer = model.NewIntVar(1, 14, 'out_yy_inner_inner_inner_inner_outer')
out_yy_inner_inner_inner_inner_inner = model.NewIntVar(1, 14, 'out_yy_inner_inner_inner_inner_inner')
outxx_inner_inner_inner_innertileSpatial = model.NewIntVar(1, 14, 'outxx_inner_inner_inner_innertileSpatial')
out_xx_inner_inner_inner_inner_outer = model.NewIntVar(1, 14, 'out_xx_inner_inner_inner_inner_outer')
out_xx_inner_inner_inner_inner_inner = model.NewIntVar(1, 14, 'out_xx_inner_inner_inner_inner_inner')
outff_inner_inner_inner_innertileSpatial = model.NewIntVar(1, 256, 'outff_inner_inner_inner_innertileSpatial')
out_ff_inner_inner_inner_inner_outer = model.NewIntVar(1, 256, 'out_ff_inner_inner_inner_inner_outer')
out_ff_inner_inner_inner_inner_inner = model.NewIntVar(1, 256, 'out_ff_inner_inner_inner_inner_inner')
out_nn_inner_inner_inner_inner_inner_yy_inner_inner_inner_inner_inner_fused_xx_inner_inner_inner_inner_inner_fused_ff_inner_inner_inner_inner_inner_fused = model.NewIntVar(1, 1000000, 'out_nn_inner_inner_inner_inner_inner_yy_inner_inner_inner_inner_inner_fused_xx_inner_inner_inner_inner_inner_fused_ff_inner_inner_inner_inner_inner_fused')
out_nn_inner_inner_inner_inner_inner_out_yy_inner_inner_inner_inner_inner = model.NewIntVar(1, 1000000, 'out_nn_inner_inner_inner_inner_inner_out_yy_inner_inner_inner_inner_inner')
out_nn_inner_inner_inner_inner_inner_out_yy_inner_inner_inner_inner_inner_out_xx_inner_inner_inner_inner_inner = model.NewIntVar(1, 1000000, 'out_nn_inner_inner_inner_inner_inner_out_yy_inner_inner_inner_inner_inner_out_xx_inner_inner_inner_inner_inner')
out_wmma_accumulator_shared_ax0 = model.NewIntVar(1, 16, 'out_wmma_accumulator_shared_ax0')
out_shared_pos_select0 = model.NewIntVar(0, 1, 'out_shared_pos_select0')
out_shared_pos_select1 = model.NewIntVar(0, 1, 'out_shared_pos_select1')
out_shared_pos_select2 = model.NewIntVar(0, 1, 'out_shared_pos_select2')
out_shared_pos_select3 = model.NewIntVar(0, 1, 'out_shared_pos_select3')
out_shared_pos_select4 = model.NewIntVar(0, 1, 'out_shared_pos_select4')
out_shared_pos_select5 = model.NewIntVar(0, 1, 'out_shared_pos_select5')
out_wmma_accumulator_shared_ax1 = model.NewIntVar(1, 14, 'out_wmma_accumulator_shared_ax1')
out_wmma_accumulator_shared_ax2 = model.NewIntVar(1, 14, 'out_wmma_accumulator_shared_ax2')
out_wmma_accumulator_shared_ax3 = model.NewIntVar(1, 256, 'out_wmma_accumulator_shared_ax3')
out_wmma_accumulator_shared_offset = model.NewIntVar(0, 48, 'out_wmma_accumulator_shared_offset')
out_wmma_accumulator_shared_offset_cand0 = model.NewIntVar(0, 1, 'out_wmma_accumulator_shared_offset_cand0')
out_wmma_accumulator_shared_offset_cand1 = model.NewIntVar(0, 1, 'out_wmma_accumulator_shared_offset_cand1')
out_wmma_accumulator_shared_offset_cand2 = model.NewIntVar(0, 1, 'out_wmma_accumulator_shared_offset_cand2')
out_wmma_accumulator_shared_offset_cand3 = model.NewIntVar(0, 1, 'out_wmma_accumulator_shared_offset_cand3')
out_wmma_accumulator_shared_offset_cand4 = model.NewIntVar(0, 1, 'out_wmma_accumulator_shared_offset_cand4')
out_wmma_accumulator_shared_offset_cand5 = model.NewIntVar(0, 1, 'out_wmma_accumulator_shared_offset_cand5')
out_wmma_accumulator_shared_align_size = model.NewIntVar(1, 88888888, 'out_wmma_accumulator_shared_align_size')
out_wmma_accumulator_sharedax0tileSpatial = model.NewIntVar(1, 16, 'out_wmma_accumulator_sharedax0tileSpatial')
out_wmma_accumulator_shared_ax0_outer = model.NewIntVar(1, 16, 'out_wmma_accumulator_shared_ax0_outer')
out_wmma_accumulator_shared_ax0_inner = model.NewIntVar(1, 16, 'out_wmma_accumulator_shared_ax0_inner')
out_wmma_accumulator_sharedax1tileSpatial = model.NewIntVar(1, 14, 'out_wmma_accumulator_sharedax1tileSpatial')
out_wmma_accumulator_shared_ax1_outer = model.NewIntVar(1, 14, 'out_wmma_accumulator_shared_ax1_outer')
out_wmma_accumulator_shared_ax1_inner = model.NewIntVar(1, 14, 'out_wmma_accumulator_shared_ax1_inner')
out_wmma_accumulator_sharedax2tileSpatial = model.NewIntVar(1, 14, 'out_wmma_accumulator_sharedax2tileSpatial')
out_wmma_accumulator_shared_ax2_outer = model.NewIntVar(1, 14, 'out_wmma_accumulator_shared_ax2_outer')
out_wmma_accumulator_shared_ax2_inner = model.NewIntVar(1, 14, 'out_wmma_accumulator_shared_ax2_inner')
out_wmma_accumulator_sharedax3tileSpatial = model.NewIntVar(1, 256, 'out_wmma_accumulator_sharedax3tileSpatial')
out_wmma_accumulator_shared_ax3_outer = model.NewIntVar(1, 256, 'out_wmma_accumulator_shared_ax3_outer')
out_wmma_accumulator_shared_ax3_inner = model.NewIntVar(1, 256, 'out_wmma_accumulator_shared_ax3_inner')
out_wmma_accumulator_sharedax0tileSpatial_out_wmma_accumulator_sharedax1tileSpatial = model.NewIntVar(1, 1024, 'out_wmma_accumulator_sharedax0tileSpatial_out_wmma_accumulator_sharedax1tileSpatial')
out_wmma_accumulator_sharedax0tileSpatial_out_wmma_accumulator_sharedax1tileSpatial_out_wmma_accumulator_sharedax2tileSpatial = model.NewIntVar(1, 1024, 'out_wmma_accumulator_sharedax0tileSpatial_out_wmma_accumulator_sharedax1tileSpatial_out_wmma_accumulator_sharedax2tileSpatial')
out_wmma_accumulator_shared_ax0_outer_ax1_outer_fused_ax2_outer_fused_ax3_outer_fused = model.NewIntVar(1, 1000000, 'out_wmma_accumulator_shared_ax0_outer_ax1_outer_fused_ax2_outer_fused_ax3_outer_fused')
out_wmma_accumulator_shared_ax0_outer_out_wmma_accumulator_shared_ax1_outer = model.NewIntVar(1, 1000000, 'out_wmma_accumulator_shared_ax0_outer_out_wmma_accumulator_shared_ax1_outer')
out_wmma_accumulator_shared_ax0_outer_out_wmma_accumulator_shared_ax1_outer_out_wmma_accumulator_shared_ax2_outer = model.NewIntVar(1, 1000000, 'out_wmma_accumulator_shared_ax0_outer_out_wmma_accumulator_shared_ax1_outer_out_wmma_accumulator_shared_ax2_outer')
out_wmma_accumulator_shared_ax0_inner_outer = model.NewIntVar(1, 16, 'out_wmma_accumulator_shared_ax0_inner_outer')
out_wmma_accumulator_shared_ax0_inner_inner = model.NewIntVar(1, 16, 'out_wmma_accumulator_shared_ax0_inner_inner')
out_wmma_accumulator_shared_ax1_inner_outer = model.NewIntVar(1, 14, 'out_wmma_accumulator_shared_ax1_inner_outer')
out_wmma_accumulator_shared_ax1_inner_inner = model.NewIntVar(1, 14, 'out_wmma_accumulator_shared_ax1_inner_inner')
out_wmma_accumulator_shared_ax2_inner_outer = model.NewIntVar(1, 14, 'out_wmma_accumulator_shared_ax2_inner_outer')
out_wmma_accumulator_shared_ax2_inner_inner = model.NewIntVar(1, 14, 'out_wmma_accumulator_shared_ax2_inner_inner')
out_wmma_accumulator_shared_ax3_inner_outer = model.NewIntVar(1, 256, 'out_wmma_accumulator_shared_ax3_inner_outer')
out_wmma_accumulator_shared_ax3_inner_inner = model.NewIntVar(1, 256, 'out_wmma_accumulator_shared_ax3_inner_inner')
out_wmma_accumulator_nn_c = model.NewIntVar(1, 16, 'out_wmma_accumulator_nn_c')
out_wmma_accumulator_shared_local_pos_select0 = model.NewIntVar(0, 1, 'out_wmma_accumulator_shared_local_pos_select0')
out_wmma_accumulator_shared_local_pos_select1 = model.NewIntVar(0, 1, 'out_wmma_accumulator_shared_local_pos_select1')
out_wmma_accumulator_yy_c = model.NewIntVar(1, 14, 'out_wmma_accumulator_yy_c')
out_wmma_accumulator_xx_c = model.NewIntVar(1, 14, 'out_wmma_accumulator_xx_c')
out_wmma_accumulator_ff_c = model.NewIntVar(1, 256, 'out_wmma_accumulator_ff_c')
out_wmma_accumulatornn_ctileAll = model.NewIntVar(1, 16, 'out_wmma_accumulatornn_ctileAll')
out_wmma_accumulator_nn_c_outer = model.NewIntVar(1, 16, 'out_wmma_accumulator_nn_c_outer')
out_wmma_accumulator_nn_c_inner = model.NewIntVar(1, 16, 'out_wmma_accumulator_nn_c_inner')
out_wmma_accumulatoryy_ctileAll = model.NewIntVar(1, 14, 'out_wmma_accumulatoryy_ctileAll')
out_wmma_accumulator_yy_c_outer = model.NewIntVar(1, 14, 'out_wmma_accumulator_yy_c_outer')
out_wmma_accumulator_yy_c_inner = model.NewIntVar(1, 14, 'out_wmma_accumulator_yy_c_inner')
out_wmma_accumulatorxx_ctileAll = model.NewIntVar(1, 14, 'out_wmma_accumulatorxx_ctileAll')
out_wmma_accumulator_xx_c_outer = model.NewIntVar(1, 14, 'out_wmma_accumulator_xx_c_outer')
out_wmma_accumulator_xx_c_inner = model.NewIntVar(1, 14, 'out_wmma_accumulator_xx_c_inner')
out_wmma_accumulatorff_ctileAll = model.NewIntVar(1, 256, 'out_wmma_accumulatorff_ctileAll')
out_wmma_accumulator_ff_c_outer = model.NewIntVar(1, 256, 'out_wmma_accumulator_ff_c_outer')
out_wmma_accumulator_ff_c_inner = model.NewIntVar(1, 256, 'out_wmma_accumulator_ff_c_inner')
out_wmma_accumulatorrytileAll = model.NewIntVar(1, 1, 'out_wmma_accumulatorrytileAll')
out_wmma_accumulator_ry_outer = model.NewIntVar(1, 1, 'out_wmma_accumulator_ry_outer')
out_wmma_accumulator_ry_inner = model.NewIntVar(1, 1, 'out_wmma_accumulator_ry_inner')
out_wmma_accumulatorrxtileAll = model.NewIntVar(1, 1, 'out_wmma_accumulatorrxtileAll')
out_wmma_accumulator_rx_outer = model.NewIntVar(1, 1, 'out_wmma_accumulator_rx_outer')
out_wmma_accumulator_rx_inner = model.NewIntVar(1, 1, 'out_wmma_accumulator_rx_inner')
out_wmma_accumulatorrctileAll = model.NewIntVar(1, 128, 'out_wmma_accumulatorrctileAll')
out_wmma_accumulator_rc_outer = model.NewIntVar(1, 128, 'out_wmma_accumulator_rc_outer')
out_wmma_accumulator_rc_inner = model.NewIntVar(1, 128, 'out_wmma_accumulator_rc_inner')
out_wmma_accumulatornn_c_innertileAll = model.NewIntVar(1, 16, 'out_wmma_accumulatornn_c_innertileAll')
out_wmma_accumulator_nn_c_inner_outer = model.NewIntVar(1, 16, 'out_wmma_accumulator_nn_c_inner_outer')
out_wmma_accumulator_nn_c_inner_inner = model.NewIntVar(1, 16, 'out_wmma_accumulator_nn_c_inner_inner')
out_wmma_accumulatoryy_c_innertileAll = model.NewIntVar(1, 14, 'out_wmma_accumulatoryy_c_innertileAll')
out_wmma_accumulator_yy_c_inner_outer = model.NewIntVar(1, 14, 'out_wmma_accumulator_yy_c_inner_outer')
out_wmma_accumulator_yy_c_inner_inner = model.NewIntVar(1, 14, 'out_wmma_accumulator_yy_c_inner_inner')
out_wmma_accumulatorxx_c_innertileAll = model.NewIntVar(1, 14, 'out_wmma_accumulatorxx_c_innertileAll')
out_wmma_accumulator_xx_c_inner_outer = model.NewIntVar(1, 14, 'out_wmma_accumulator_xx_c_inner_outer')
out_wmma_accumulator_xx_c_inner_inner = model.NewIntVar(1, 14, 'out_wmma_accumulator_xx_c_inner_inner')
out_wmma_accumulatorff_c_innertileAll = model.NewIntVar(1, 256, 'out_wmma_accumulatorff_c_innertileAll')
out_wmma_accumulator_ff_c_inner_outer = model.NewIntVar(1, 256, 'out_wmma_accumulator_ff_c_inner_outer')
out_wmma_accumulator_ff_c_inner_inner = model.NewIntVar(1, 256, 'out_wmma_accumulator_ff_c_inner_inner')
out_wmma_accumulatorry_innertileAll = model.NewIntVar(1, 1, 'out_wmma_accumulatorry_innertileAll')
out_wmma_accumulator_ry_inner_outer = model.NewIntVar(1, 1, 'out_wmma_accumulator_ry_inner_outer')
out_wmma_accumulator_ry_inner_inner = model.NewIntVar(1, 1, 'out_wmma_accumulator_ry_inner_inner')
out_wmma_accumulatorrx_innertileAll = model.NewIntVar(1, 1, 'out_wmma_accumulatorrx_innertileAll')
out_wmma_accumulator_rx_inner_outer = model.NewIntVar(1, 1, 'out_wmma_accumulator_rx_inner_outer')
out_wmma_accumulator_rx_inner_inner = model.NewIntVar(1, 1, 'out_wmma_accumulator_rx_inner_inner')
out_wmma_accumulatorrc_innertileAll = model.NewIntVar(1, 128, 'out_wmma_accumulatorrc_innertileAll')
out_wmma_accumulator_rc_inner_outer = model.NewIntVar(1, 128, 'out_wmma_accumulator_rc_inner_outer')
out_wmma_accumulator_rc_inner_inner = model.NewIntVar(1, 128, 'out_wmma_accumulator_rc_inner_inner')
out_wmma_accumulatornn_c_inner_innertileAll = model.NewIntVar(1, 16, 'out_wmma_accumulatornn_c_inner_innertileAll')
out_wmma_accumulator_nn_c_inner_inner_outer = model.NewIntVar(1, 16, 'out_wmma_accumulator_nn_c_inner_inner_outer')
out_wmma_accumulator_nn_c_inner_inner_inner = model.NewIntVar(1, 16, 'out_wmma_accumulator_nn_c_inner_inner_inner')
out_wmma_accumulatoryy_c_inner_innertileAll = model.NewIntVar(1, 14, 'out_wmma_accumulatoryy_c_inner_innertileAll')
out_wmma_accumulator_yy_c_inner_inner_outer = model.NewIntVar(1, 14, 'out_wmma_accumulator_yy_c_inner_inner_outer')
out_wmma_accumulator_yy_c_inner_inner_inner = model.NewIntVar(1, 14, 'out_wmma_accumulator_yy_c_inner_inner_inner')
out_wmma_accumulatorxx_c_inner_innertileAll = model.NewIntVar(1, 14, 'out_wmma_accumulatorxx_c_inner_innertileAll')
out_wmma_accumulator_xx_c_inner_inner_outer = model.NewIntVar(1, 14, 'out_wmma_accumulator_xx_c_inner_inner_outer')
out_wmma_accumulator_xx_c_inner_inner_inner = model.NewIntVar(1, 14, 'out_wmma_accumulator_xx_c_inner_inner_inner')
out_wmma_accumulatorff_c_inner_innertileAll = model.NewIntVar(1, 256, 'out_wmma_accumulatorff_c_inner_innertileAll')
out_wmma_accumulator_ff_c_inner_inner_outer = model.NewIntVar(1, 256, 'out_wmma_accumulator_ff_c_inner_inner_outer')
out_wmma_accumulator_ff_c_inner_inner_inner = model.NewIntVar(1, 256, 'out_wmma_accumulator_ff_c_inner_inner_inner')
out_wmma_accumulatorry_inner_innertileAll = model.NewIntVar(1, 1, 'out_wmma_accumulatorry_inner_innertileAll')
out_wmma_accumulator_ry_inner_inner_outer = model.NewIntVar(1, 1, 'out_wmma_accumulator_ry_inner_inner_outer')
out_wmma_accumulator_ry_inner_inner_inner = model.NewIntVar(1, 1, 'out_wmma_accumulator_ry_inner_inner_inner')
out_wmma_accumulatorrx_inner_innertileAll = model.NewIntVar(1, 1, 'out_wmma_accumulatorrx_inner_innertileAll')
out_wmma_accumulator_rx_inner_inner_outer = model.NewIntVar(1, 1, 'out_wmma_accumulator_rx_inner_inner_outer')
out_wmma_accumulator_rx_inner_inner_inner = model.NewIntVar(1, 1, 'out_wmma_accumulator_rx_inner_inner_inner')
out_wmma_accumulatorrc_inner_innertileAll = model.NewIntVar(1, 128, 'out_wmma_accumulatorrc_inner_innertileAll')
out_wmma_accumulator_rc_inner_inner_outer = model.NewIntVar(1, 128, 'out_wmma_accumulator_rc_inner_inner_outer')
out_wmma_accumulator_rc_inner_inner_inner = model.NewIntVar(1, 128, 'out_wmma_accumulator_rc_inner_inner_inner')
out_wmma_accumulator_nn_c_inner_inner_inner_outer = model.NewIntVar(1, 16, 'out_wmma_accumulator_nn_c_inner_inner_inner_outer')
out_wmma_accumulator_nn_c_inner_inner_inner_inner = model.NewIntVar(1, 16, 'out_wmma_accumulator_nn_c_inner_inner_inner_inner')
out_wmma_accumulator_yy_c_inner_inner_inner_outer = model.NewIntVar(1, 14, 'out_wmma_accumulator_yy_c_inner_inner_inner_outer')
out_wmma_accumulator_yy_c_inner_inner_inner_inner = model.NewIntVar(1, 14, 'out_wmma_accumulator_yy_c_inner_inner_inner_inner')
out_wmma_accumulator_xx_c_inner_inner_inner_outer = model.NewIntVar(1, 14, 'out_wmma_accumulator_xx_c_inner_inner_inner_outer')
out_wmma_accumulator_xx_c_inner_inner_inner_inner = model.NewIntVar(1, 14, 'out_wmma_accumulator_xx_c_inner_inner_inner_inner')
out_wmma_accumulator_ff_c_inner_inner_inner_outer = model.NewIntVar(1, 256, 'out_wmma_accumulator_ff_c_inner_inner_inner_outer')
out_wmma_accumulator_ff_c_inner_inner_inner_inner = model.NewIntVar(1, 256, 'out_wmma_accumulator_ff_c_inner_inner_inner_inner')
out_wmma_accumulator_ry_inner_inner_inner_outer = model.NewIntVar(1, 1, 'out_wmma_accumulator_ry_inner_inner_inner_outer')
out_wmma_accumulator_ry_inner_inner_inner_inner = model.NewIntVar(1, 1, 'out_wmma_accumulator_ry_inner_inner_inner_inner')
out_wmma_accumulator_rx_inner_inner_inner_outer = model.NewIntVar(1, 1, 'out_wmma_accumulator_rx_inner_inner_inner_outer')
out_wmma_accumulator_rx_inner_inner_inner_inner = model.NewIntVar(1, 1, 'out_wmma_accumulator_rx_inner_inner_inner_inner')
out_wmma_accumulator_rc_inner_inner_inner_outer = model.NewIntVar(1, 128, 'out_wmma_accumulator_rc_inner_inner_inner_outer')
out_wmma_accumulator_rc_inner_inner_inner_inner = model.NewIntVar(1, 128, 'out_wmma_accumulator_rc_inner_inner_inner_inner')
filter_shared_wmma_matrix_b_ax0 = model.NewIntVar(1, 1, 'filter_shared_wmma_matrix_b_ax0')
out_wmma_accumulator_local_pos_select0 = model.NewIntVar(0, 1, 'out_wmma_accumulator_local_pos_select0')
out_wmma_accumulator_local_pos_select1 = model.NewIntVar(0, 1, 'out_wmma_accumulator_local_pos_select1')
out_wmma_accumulator_local_pos_select2 = model.NewIntVar(0, 1, 'out_wmma_accumulator_local_pos_select2')
out_wmma_accumulator_local_pos_select3 = model.NewIntVar(0, 1, 'out_wmma_accumulator_local_pos_select3')
filter_shared_wmma_matrix_b_ax1 = model.NewIntVar(1, 1, 'filter_shared_wmma_matrix_b_ax1')
filter_shared_wmma_matrix_b_ax2 = model.NewIntVar(1, 128, 'filter_shared_wmma_matrix_b_ax2')
filter_shared_wmma_matrix_b_ax3 = model.NewIntVar(1, 256, 'filter_shared_wmma_matrix_b_ax3')
filter_shared_wmma_matrix_b_ax0_outer = model.NewIntVar(1, 1, 'filter_shared_wmma_matrix_b_ax0_outer')
filter_shared_wmma_matrix_b_ax0_inner = model.NewIntVar(1, 1, 'filter_shared_wmma_matrix_b_ax0_inner')
filter_shared_wmma_matrix_b_ax1_outer = model.NewIntVar(1, 1, 'filter_shared_wmma_matrix_b_ax1_outer')
filter_shared_wmma_matrix_b_ax1_inner = model.NewIntVar(1, 1, 'filter_shared_wmma_matrix_b_ax1_inner')
filter_shared_wmma_matrix_b_ax2_outer = model.NewIntVar(1, 128, 'filter_shared_wmma_matrix_b_ax2_outer')
filter_shared_wmma_matrix_b_ax2_inner = model.NewIntVar(1, 128, 'filter_shared_wmma_matrix_b_ax2_inner')
filter_shared_wmma_matrix_b_ax3_outer = model.NewIntVar(1, 256, 'filter_shared_wmma_matrix_b_ax3_outer')
filter_shared_wmma_matrix_b_ax3_inner = model.NewIntVar(1, 256, 'filter_shared_wmma_matrix_b_ax3_inner')
filter_shared_ax0 = model.NewIntVar(1, 1, 'filter_shared_ax0')
out_wmma_accumulator_shared_pos_select0 = model.NewIntVar(0, 1, 'out_wmma_accumulator_shared_pos_select0')
out_wmma_accumulator_shared_pos_select1 = model.NewIntVar(0, 1, 'out_wmma_accumulator_shared_pos_select1')
out_wmma_accumulator_shared_pos_select2 = model.NewIntVar(0, 1, 'out_wmma_accumulator_shared_pos_select2')
out_wmma_accumulator_shared_pos_select3 = model.NewIntVar(0, 1, 'out_wmma_accumulator_shared_pos_select3')
filter_shared_ax1 = model.NewIntVar(1, 1, 'filter_shared_ax1')
filter_shared_ax2 = model.NewIntVar(1, 128, 'filter_shared_ax2')
filter_shared_ax3 = model.NewIntVar(1, 256, 'filter_shared_ax3')
filter_shared_tmp_ax3 = model.NewIntVar(1, 256, 'filter_shared_tmp_ax3')
filter_shared_offset = model.NewIntVar(0, 48, 'filter_shared_offset')
filter_shared_offset_cand0 = model.NewIntVar(0, 1, 'filter_shared_offset_cand0')
filter_shared_offset_cand1 = model.NewIntVar(0, 1, 'filter_shared_offset_cand1')
filter_shared_offset_cand2 = model.NewIntVar(0, 1, 'filter_shared_offset_cand2')
filter_shared_offset_cand3 = model.NewIntVar(0, 1, 'filter_shared_offset_cand3')
filter_shared_offset_cand4 = model.NewIntVar(0, 1, 'filter_shared_offset_cand4')
filter_shared_offset_cand5 = model.NewIntVar(0, 1, 'filter_shared_offset_cand5')
filter_shared_align_size = model.NewIntVar(1, 88888888, 'filter_shared_align_size')
filter_shared_ax0_ax1_fused_ax2_fused_ax3_fused = model.NewIntVar(1, 1000000, 'filter_shared_ax0_ax1_fused_ax2_fused_ax3_fused')
filter_shared_ax0_filter_shared_ax1 = model.NewIntVar(1, 1000000, 'filter_shared_ax0_filter_shared_ax1')
filter_shared_ax0_filter_shared_ax1_filter_shared_ax2 = model.NewIntVar(1, 1000000, 'filter_shared_ax0_filter_shared_ax1_filter_shared_ax2')
filter_shared_vectorize = model.NewIntVar(1, 8, 'filter_shared_vectorize')
filter_shared_vectorize_cand0 = model.NewIntVar(0, 1, 'filter_shared_vectorize_cand0')
filter_shared_vectorize_cand1 = model.NewIntVar(0, 1, 'filter_shared_vectorize_cand1')
filter_shared_vectorize_cand2 = model.NewIntVar(0, 1, 'filter_shared_vectorize_cand2')
filter_shared_vectorize_cand3 = model.NewIntVar(0, 1, 'filter_shared_vectorize_cand3')
PaddedInput_shared_wmma_matrix_a_ax0 = model.NewIntVar(1, 16, 'PaddedInput_shared_wmma_matrix_a_ax0')
PaddedInput_shared_wmma_matrix_a_ax1 = model.NewIntVar(1, 14, 'PaddedInput_shared_wmma_matrix_a_ax1')
PaddedInput_shared_wmma_matrix_a_ax2 = model.NewIntVar(1, 14, 'PaddedInput_shared_wmma_matrix_a_ax2')
PaddedInput_shared_wmma_matrix_a_ax3 = model.NewIntVar(1, 128, 'PaddedInput_shared_wmma_matrix_a_ax3')
PaddedInput_shared_wmma_matrix_a_ax0_outer = model.NewIntVar(1, 16, 'PaddedInput_shared_wmma_matrix_a_ax0_outer')
PaddedInput_shared_wmma_matrix_a_ax0_inner = model.NewIntVar(1, 16, 'PaddedInput_shared_wmma_matrix_a_ax0_inner')
PaddedInput_shared_wmma_matrix_a_ax1_outer = model.NewIntVar(1, 28, 'PaddedInput_shared_wmma_matrix_a_ax1_outer')
PaddedInput_shared_wmma_matrix_a_ax1_inner = model.NewIntVar(1, 28, 'PaddedInput_shared_wmma_matrix_a_ax1_inner')
PaddedInput_shared_wmma_matrix_a_ax2_outer = model.NewIntVar(1, 28, 'PaddedInput_shared_wmma_matrix_a_ax2_outer')
PaddedInput_shared_wmma_matrix_a_ax2_inner = model.NewIntVar(1, 28, 'PaddedInput_shared_wmma_matrix_a_ax2_inner')
PaddedInput_shared_wmma_matrix_a_ax3_outer = model.NewIntVar(1, 128, 'PaddedInput_shared_wmma_matrix_a_ax3_outer')
PaddedInput_shared_wmma_matrix_a_ax3_inner = model.NewIntVar(1, 128, 'PaddedInput_shared_wmma_matrix_a_ax3_inner')
PaddedInput_shared_ax0 = model.NewIntVar(1, 16, 'PaddedInput_shared_ax0')
PaddedInput_shared_tmp_ax0 = model.NewIntVar(1, 16, 'PaddedInput_shared_tmp_ax0')
PaddedInput_shared_ax1 = model.NewIntVar(1, 14, 'PaddedInput_shared_ax1')
PaddedInput_shared_tmp_ax1 = model.NewIntVar(1, 14, 'PaddedInput_shared_tmp_ax1')
PaddedInput_shared_ax2 = model.NewIntVar(1, 14, 'PaddedInput_shared_ax2')
PaddedInput_shared_tmp_ax2 = model.NewIntVar(1, 14, 'PaddedInput_shared_tmp_ax2')
PaddedInput_shared_ax3 = model.NewIntVar(1, 128, 'PaddedInput_shared_ax3')
PaddedInput_shared_offset = model.NewIntVar(0, 48, 'PaddedInput_shared_offset')
PaddedInput_shared_offset_cand0 = model.NewIntVar(0, 1, 'PaddedInput_shared_offset_cand0')
PaddedInput_shared_offset_cand1 = model.NewIntVar(0, 1, 'PaddedInput_shared_offset_cand1')
PaddedInput_shared_offset_cand2 = model.NewIntVar(0, 1, 'PaddedInput_shared_offset_cand2')
PaddedInput_shared_offset_cand3 = model.NewIntVar(0, 1, 'PaddedInput_shared_offset_cand3')
PaddedInput_shared_offset_cand4 = model.NewIntVar(0, 1, 'PaddedInput_shared_offset_cand4')
PaddedInput_shared_offset_cand5 = model.NewIntVar(0, 1, 'PaddedInput_shared_offset_cand5')
PaddedInput_shared_align_size = model.NewIntVar(1, 88888888, 'PaddedInput_shared_align_size')
PaddedInput_shared_ax0_ax1_fused_ax2_fused_ax3_fused = model.NewIntVar(1, 1000000, 'PaddedInput_shared_ax0_ax1_fused_ax2_fused_ax3_fused')
PaddedInput_shared_ax0_PaddedInput_shared_ax1 = model.NewIntVar(1, 1000000, 'PaddedInput_shared_ax0_PaddedInput_shared_ax1')
PaddedInput_shared_ax0_PaddedInput_shared_ax1_PaddedInput_shared_ax2 = model.NewIntVar(1, 1000000, 'PaddedInput_shared_ax0_PaddedInput_shared_ax1_PaddedInput_shared_ax2')
PaddedInput_shared_vectorize = model.NewIntVar(1, 8, 'PaddedInput_shared_vectorize')
PaddedInput_shared_vectorize_cand0 = model.NewIntVar(0, 1, 'PaddedInput_shared_vectorize_cand0')
PaddedInput_shared_vectorize_cand1 = model.NewIntVar(0, 1, 'PaddedInput_shared_vectorize_cand1')
PaddedInput_shared_vectorize_cand2 = model.NewIntVar(0, 1, 'PaddedInput_shared_vectorize_cand2')
PaddedInput_shared_vectorize_cand3 = model.NewIntVar(0, 1, 'PaddedInput_shared_vectorize_cand3')
threads = model.NewIntVar(1, 1024, 'threads')
PaddedInput_shared_shared_mem_size = model.NewIntVar(1, 24576, 'PaddedInput_shared_shared_mem_size')
filter_shared_shared_mem_size = model.NewIntVar(1, 24576, 'filter_shared_shared_mem_size')
out_wmma_accumulator_shared_shared_mem_size = model.NewIntVar(1, 24576, 'out_wmma_accumulator_shared_shared_mem_size')
out_wmma_accumulator_shared_ax0_out_wmma_accumulator_shared_ax1 = model.NewIntVar(1, 24576, 'out_wmma_accumulator_shared_ax0_out_wmma_accumulator_shared_ax1')
out_wmma_accumulator_shared_ax0_out_wmma_accumulator_shared_ax1_out_wmma_accumulator_shared_ax2 = model.NewIntVar(1, 24576, 'out_wmma_accumulator_shared_ax0_out_wmma_accumulator_shared_ax1_out_wmma_accumulator_shared_ax2')
model.Add(wmma_m == 8).OnlyEnforceIf(wmma_m_cand0)
model.Add(wmma_m == 16).OnlyEnforceIf(wmma_m_cand1)
model.Add(wmma_m == 32).OnlyEnforceIf(wmma_m_cand2)
model.Add(sum([wmma_m_cand0, wmma_m_cand1, wmma_m_cand2]) == 1)
model.Add(wmma_n == 8).OnlyEnforceIf(wmma_n_cand0)
model.Add(wmma_n == 16).OnlyEnforceIf(wmma_n_cand1)
model.Add(wmma_n == 32).OnlyEnforceIf(wmma_n_cand2)
model.Add(sum([wmma_n_cand0, wmma_n_cand1, wmma_n_cand2]) == 1)
model.AddMultiplicationEquality(wmma_m_wmma_n, [wmma_m, wmma_n])
model.AddMultiplicationEquality(4096, [wmma_m_wmma_n, wmma_k])
model.AddMultiplicationEquality(16, [out_nn_outer, out_nn_inner])
model.Add(out_nn_outer == 1)
model.AddMultiplicationEquality(14, [out_yy_outer, out_yy_inner])
model.Add(out_yy_outer == 1)
model.AddMultiplicationEquality(14, [out_xx_outer, out_xx_inner])
model.Add(out_xx_outer == 1)
model.AddMultiplicationEquality(256, [out_ff_outer, out_ff_inner])
model.Add(out_ff_outer == 1)
model.AddMultiplicationEquality(out_nn_inner, [out_nn_inner_outer, out_nn_inner_inner])
model.Add(out_nn_inner_outer == outnn_innertileSpatial)
model.AddMultiplicationEquality(out_yy_inner, [out_yy_inner_outer, out_yy_inner_inner])
model.Add(out_yy_inner_outer == outyy_innertileSpatial)
model.AddMultiplicationEquality(out_xx_inner, [out_xx_inner_outer, out_xx_inner_inner])
model.Add(out_xx_inner_outer == outxx_innertileSpatial)
model.AddMultiplicationEquality(out_ff_inner, [out_ff_inner_outer, out_ff_inner_inner])
model.Add(out_ff_inner_outer == outff_innertileSpatial)
model.AddMultiplicationEquality(outnn_innertileSpatial_outyy_innertileSpatial, [outnn_innertileSpatial, outyy_innertileSpatial])
model.AddMultiplicationEquality(outnn_innertileSpatial_outyy_innertileSpatial_outxx_innertileSpatial, [outnn_innertileSpatial_outyy_innertileSpatial, outxx_innertileSpatial])
model.AddMultiplicationEquality(blockIdx_x, [outnn_innertileSpatial_outyy_innertileSpatial_outxx_innertileSpatial, outff_innertileSpatial])
model.AddMultiplicationEquality(out_nn_inner_outer_out_yy_inner_outer, [out_nn_inner_outer, out_yy_inner_outer])
model.AddMultiplicationEquality(out_nn_inner_outer_out_yy_inner_outer_out_xx_inner_outer, [out_nn_inner_outer_out_yy_inner_outer, out_xx_inner_outer])
model.AddMultiplicationEquality(out_nn_inner_outer_yy_inner_outer_fused_xx_inner_outer_fused_ff_inner_outer_fused, [out_nn_inner_outer_out_yy_inner_outer_out_xx_inner_outer, out_ff_inner_outer])
model.AddMultiplicationEquality(out_nn_inner_inner, [out_nn_inner_inner_outer, out_nn_inner_inner_inner])
model.Add(out_nn_inner_inner_outer == outnn_inner_innertileSpatial)
model.AddMultiplicationEquality(out_yy_inner_inner, [out_yy_inner_inner_outer, out_yy_inner_inner_inner])
model.Add(out_yy_inner_inner_outer == outyy_inner_innertileSpatial)
model.AddMultiplicationEquality(out_xx_inner_inner, [out_xx_inner_inner_outer, out_xx_inner_inner_inner])
model.Add(out_xx_inner_inner_outer == outxx_inner_innertileSpatial)
model.AddMultiplicationEquality(out_ff_inner_inner, [out_ff_inner_inner_outer, out_ff_inner_inner_inner])
model.Add(out_ff_inner_inner_outer == outff_inner_innertileSpatial)
model.AddMultiplicationEquality(outnn_inner_innertileSpatial_outyy_inner_innertileSpatial, [outnn_inner_innertileSpatial, outyy_inner_innertileSpatial])
model.AddMultiplicationEquality(outnn_inner_innertileSpatial_outyy_inner_innertileSpatial_outxx_inner_innertileSpatial, [outnn_inner_innertileSpatial_outyy_inner_innertileSpatial, outxx_inner_innertileSpatial])
model.AddMultiplicationEquality(threadIdx_y, [outnn_inner_innertileSpatial_outyy_inner_innertileSpatial_outxx_inner_innertileSpatial, outff_inner_innertileSpatial])
model.AddMultiplicationEquality(out_nn_inner_inner_outer_out_yy_inner_inner_outer, [out_nn_inner_inner_outer, out_yy_inner_inner_outer])
model.AddMultiplicationEquality(out_nn_inner_inner_outer_out_yy_inner_inner_outer_out_xx_inner_inner_outer, [out_nn_inner_inner_outer_out_yy_inner_inner_outer, out_xx_inner_inner_outer])
model.AddMultiplicationEquality(out_nn_inner_inner_outer_yy_inner_inner_outer_fused_xx_inner_inner_outer_fused_ff_inner_inner_outer_fused, [out_nn_inner_inner_outer_out_yy_inner_inner_outer_out_xx_inner_inner_outer, out_ff_inner_inner_outer])
model.AddMultiplicationEquality(out_nn_inner_inner_inner, [out_nn_inner_inner_inner_outer, out_nn_inner_inner_inner_inner])
model.Add(out_nn_inner_inner_inner_outer == outnn_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(out_yy_inner_inner_inner, [out_yy_inner_inner_inner_outer, out_yy_inner_inner_inner_inner])
model.Add(out_yy_inner_inner_inner_outer == outyy_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(out_xx_inner_inner_inner, [out_xx_inner_inner_inner_outer, out_xx_inner_inner_inner_inner])
model.Add(out_xx_inner_inner_inner_outer == outxx_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(out_ff_inner_inner_inner, [out_ff_inner_inner_inner_outer, out_ff_inner_inner_inner_inner])
model.Add(out_ff_inner_inner_inner_outer == outff_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(outnn_inner_inner_innertileSpatial_outyy_inner_inner_innertileSpatial, [outnn_inner_inner_innertileSpatial, outyy_inner_inner_innertileSpatial])
model.AddMultiplicationEquality(outnn_inner_inner_innertileSpatial_outyy_inner_inner_innertileSpatial_outxx_inner_inner_innertileSpatial, [outnn_inner_inner_innertileSpatial_outyy_inner_inner_innertileSpatial, outxx_inner_inner_innertileSpatial])
model.AddMultiplicationEquality(threadIdx_x, [outnn_inner_inner_innertileSpatial_outyy_inner_inner_innertileSpatial_outxx_inner_inner_innertileSpatial, outff_inner_inner_innertileSpatial])
model.AddMultiplicationEquality(out_nn_inner_inner_inner_outer_out_yy_inner_inner_inner_outer, [out_nn_inner_inner_inner_outer, out_yy_inner_inner_inner_outer])
model.AddMultiplicationEquality(out_nn_inner_inner_inner_outer_out_yy_inner_inner_inner_outer_out_xx_inner_inner_inner_outer, [out_nn_inner_inner_inner_outer_out_yy_inner_inner_inner_outer, out_xx_inner_inner_inner_outer])
model.AddMultiplicationEquality(out_nn_inner_inner_inner_outer_yy_inner_inner_inner_outer_fused_xx_inner_inner_inner_outer_fused_ff_inner_inner_inner_outer_fused, [out_nn_inner_inner_inner_outer_out_yy_inner_inner_inner_outer_out_xx_inner_inner_inner_outer, out_ff_inner_inner_inner_outer])
model.Add(out_vectorize == 1).OnlyEnforceIf(out_vectorize_cand0)
model.Add(out_vectorize == 2).OnlyEnforceIf(out_vectorize_cand1)
model.Add(out_vectorize == 4).OnlyEnforceIf(out_vectorize_cand2)
model.Add(out_vectorize == 8).OnlyEnforceIf(out_vectorize_cand3)
model.Add(sum([out_vectorize_cand0, out_vectorize_cand1, out_vectorize_cand2, out_vectorize_cand3]) == 1)
model.AddMultiplicationEquality(out_nn_inner_inner_inner_inner, [out_nn_inner_inner_inner_inner_outer, out_nn_inner_inner_inner_inner_inner])
model.Add(out_nn_inner_inner_inner_inner_outer == outnn_inner_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(out_yy_inner_inner_inner_inner, [out_yy_inner_inner_inner_inner_outer, out_yy_inner_inner_inner_inner_inner])
model.Add(out_yy_inner_inner_inner_inner_outer == outyy_inner_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(out_xx_inner_inner_inner_inner, [out_xx_inner_inner_inner_inner_outer, out_xx_inner_inner_inner_inner_inner])
model.Add(out_xx_inner_inner_inner_inner_outer == outxx_inner_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(out_ff_inner_inner_inner_inner, [out_ff_inner_inner_inner_inner_outer, out_ff_inner_inner_inner_inner_inner])
model.Add(out_ff_inner_inner_inner_inner_outer == outff_inner_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(out_nn_inner_inner_inner_inner_inner_out_yy_inner_inner_inner_inner_inner, [out_nn_inner_inner_inner_inner_inner, out_yy_inner_inner_inner_inner_inner])
model.AddMultiplicationEquality(out_nn_inner_inner_inner_inner_inner_out_yy_inner_inner_inner_inner_inner_out_xx_inner_inner_inner_inner_inner, [out_nn_inner_inner_inner_inner_inner_out_yy_inner_inner_inner_inner_inner, out_xx_inner_inner_inner_inner_inner])
model.AddMultiplicationEquality(out_nn_inner_inner_inner_inner_inner_yy_inner_inner_inner_inner_inner_fused_xx_inner_inner_inner_inner_inner_fused_ff_inner_inner_inner_inner_inner_fused, [out_nn_inner_inner_inner_inner_inner_out_yy_inner_inner_inner_inner_inner_out_xx_inner_inner_inner_inner_inner, out_ff_inner_inner_inner_inner_inner])
model.Add(out_nn_inner_inner_inner_inner_inner_yy_inner_inner_inner_inner_inner_fused_xx_inner_inner_inner_inner_inner_fused_ff_inner_inner_inner_inner_inner_fused == out_vectorize)
model.Add(out_shared_pos != 0)
model.Add(out_wmma_accumulator_shared_ax0 == out_nn_inner).OnlyEnforceIf(out_shared_pos_select0)
model.Add(out_shared_pos == 0).OnlyEnforceIf(out_shared_pos_select0)
model.Add(out_wmma_accumulator_shared_ax0 == out_nn_inner_inner).OnlyEnforceIf(out_shared_pos_select1)
model.Add(out_shared_pos == 1).OnlyEnforceIf(out_shared_pos_select1)
model.Add(out_wmma_accumulator_shared_ax0 == out_nn_inner_inner_inner).OnlyEnforceIf(out_shared_pos_select2)
model.Add(out_shared_pos == 2).OnlyEnforceIf(out_shared_pos_select2)
model.Add(out_wmma_accumulator_shared_ax0 == out_nn_inner_inner_inner_inner).OnlyEnforceIf(out_shared_pos_select3)
model.Add(out_shared_pos == 3).OnlyEnforceIf(out_shared_pos_select3)
model.Add(out_wmma_accumulator_shared_ax0 == out_nn_inner_inner_inner_inner_inner).OnlyEnforceIf(out_shared_pos_select4)
model.Add(out_shared_pos == 4).OnlyEnforceIf(out_shared_pos_select4)
model.Add(out_wmma_accumulator_shared_ax0 == 1).OnlyEnforceIf(out_shared_pos_select5)
model.Add(out_shared_pos == 5).OnlyEnforceIf(out_shared_pos_select5)
model.Add(sum([out_shared_pos_select0, out_shared_pos_select1, out_shared_pos_select2, out_shared_pos_select3, out_shared_pos_select4, out_shared_pos_select5]) == 1)
model.Add(out_wmma_accumulator_shared_ax1 == out_yy_inner).OnlyEnforceIf(out_shared_pos_select0)
model.Add(out_shared_pos == 0).OnlyEnforceIf(out_shared_pos_select0)
model.Add(out_wmma_accumulator_shared_ax1 == out_yy_inner_inner).OnlyEnforceIf(out_shared_pos_select1)
model.Add(out_shared_pos == 1).OnlyEnforceIf(out_shared_pos_select1)
model.Add(out_wmma_accumulator_shared_ax1 == out_yy_inner_inner_inner).OnlyEnforceIf(out_shared_pos_select2)
model.Add(out_shared_pos == 2).OnlyEnforceIf(out_shared_pos_select2)
model.Add(out_wmma_accumulator_shared_ax1 == out_yy_inner_inner_inner_inner).OnlyEnforceIf(out_shared_pos_select3)
model.Add(out_shared_pos == 3).OnlyEnforceIf(out_shared_pos_select3)
model.Add(out_wmma_accumulator_shared_ax1 == out_yy_inner_inner_inner_inner_inner).OnlyEnforceIf(out_shared_pos_select4)
model.Add(out_shared_pos == 4).OnlyEnforceIf(out_shared_pos_select4)
model.Add(out_wmma_accumulator_shared_ax1 == 1).OnlyEnforceIf(out_shared_pos_select5)
model.Add(out_shared_pos == 5).OnlyEnforceIf(out_shared_pos_select5)
model.Add(sum([out_shared_pos_select0, out_shared_pos_select1, out_shared_pos_select2, out_shared_pos_select3, out_shared_pos_select4, out_shared_pos_select5]) == 1)
model.Add(out_wmma_accumulator_shared_ax2 == out_xx_inner).OnlyEnforceIf(out_shared_pos_select0)
model.Add(out_shared_pos == 0).OnlyEnforceIf(out_shared_pos_select0)
model.Add(out_wmma_accumulator_shared_ax2 == out_xx_inner_inner).OnlyEnforceIf(out_shared_pos_select1)
model.Add(out_shared_pos == 1).OnlyEnforceIf(out_shared_pos_select1)
model.Add(out_wmma_accumulator_shared_ax2 == out_xx_inner_inner_inner).OnlyEnforceIf(out_shared_pos_select2)
model.Add(out_shared_pos == 2).OnlyEnforceIf(out_shared_pos_select2)
model.Add(out_wmma_accumulator_shared_ax2 == out_xx_inner_inner_inner_inner).OnlyEnforceIf(out_shared_pos_select3)
model.Add(out_shared_pos == 3).OnlyEnforceIf(out_shared_pos_select3)
model.Add(out_wmma_accumulator_shared_ax2 == out_xx_inner_inner_inner_inner_inner).OnlyEnforceIf(out_shared_pos_select4)
model.Add(out_shared_pos == 4).OnlyEnforceIf(out_shared_pos_select4)
model.Add(out_wmma_accumulator_shared_ax2 == 1).OnlyEnforceIf(out_shared_pos_select5)
model.Add(out_shared_pos == 5).OnlyEnforceIf(out_shared_pos_select5)
model.Add(sum([out_shared_pos_select0, out_shared_pos_select1, out_shared_pos_select2, out_shared_pos_select3, out_shared_pos_select4, out_shared_pos_select5]) == 1)
model.Add(out_wmma_accumulator_shared_ax3 == out_ff_inner).OnlyEnforceIf(out_shared_pos_select0)
model.Add(out_shared_pos == 0).OnlyEnforceIf(out_shared_pos_select0)
model.Add(out_wmma_accumulator_shared_ax3 == out_ff_inner_inner).OnlyEnforceIf(out_shared_pos_select1)
model.Add(out_shared_pos == 1).OnlyEnforceIf(out_shared_pos_select1)
model.Add(out_wmma_accumulator_shared_ax3 == out_ff_inner_inner_inner).OnlyEnforceIf(out_shared_pos_select2)
model.Add(out_shared_pos == 2).OnlyEnforceIf(out_shared_pos_select2)
model.Add(out_wmma_accumulator_shared_ax3 == out_ff_inner_inner_inner_inner).OnlyEnforceIf(out_shared_pos_select3)
model.Add(out_shared_pos == 3).OnlyEnforceIf(out_shared_pos_select3)
model.Add(out_wmma_accumulator_shared_ax3 == out_ff_inner_inner_inner_inner_inner).OnlyEnforceIf(out_shared_pos_select4)
model.Add(out_shared_pos == 4).OnlyEnforceIf(out_shared_pos_select4)
model.Add(out_wmma_accumulator_shared_ax3 == 1).OnlyEnforceIf(out_shared_pos_select5)
model.Add(out_shared_pos == 5).OnlyEnforceIf(out_shared_pos_select5)
model.Add(sum([out_shared_pos_select0, out_shared_pos_select1, out_shared_pos_select2, out_shared_pos_select3, out_shared_pos_select4, out_shared_pos_select5]) == 1)
model.Add(out_wmma_accumulator_shared_offset == 0).OnlyEnforceIf(out_wmma_accumulator_shared_offset_cand0)
model.Add(out_wmma_accumulator_shared_offset == 8).OnlyEnforceIf(out_wmma_accumulator_shared_offset_cand1)
model.Add(out_wmma_accumulator_shared_offset == 16).OnlyEnforceIf(out_wmma_accumulator_shared_offset_cand2)
model.Add(out_wmma_accumulator_shared_offset == 24).OnlyEnforceIf(out_wmma_accumulator_shared_offset_cand3)
model.Add(out_wmma_accumulator_shared_offset == 32).OnlyEnforceIf(out_wmma_accumulator_shared_offset_cand4)
model.Add(out_wmma_accumulator_shared_offset == 48).OnlyEnforceIf(out_wmma_accumulator_shared_offset_cand5)
model.Add(sum([out_wmma_accumulator_shared_offset_cand0, out_wmma_accumulator_shared_offset_cand1, out_wmma_accumulator_shared_offset_cand2, out_wmma_accumulator_shared_offset_cand3, out_wmma_accumulator_shared_offset_cand4, out_wmma_accumulator_shared_offset_cand5]) == 1)
model.Add(sum([out_wmma_accumulator_shared_ax3, out_wmma_accumulator_shared_offset]) == out_wmma_accumulator_shared_align_size)
model.AddMultiplicationEquality(out_wmma_accumulator_shared_ax0, [out_wmma_accumulator_shared_ax0_outer, out_wmma_accumulator_shared_ax0_inner])
model.Add(out_wmma_accumulator_shared_ax0_outer == out_wmma_accumulator_sharedax0tileSpatial)
model.AddMultiplicationEquality(out_wmma_accumulator_shared_ax1, [out_wmma_accumulator_shared_ax1_outer, out_wmma_accumulator_shared_ax1_inner])
model.Add(out_wmma_accumulator_shared_ax1_outer == out_wmma_accumulator_sharedax1tileSpatial)
model.AddMultiplicationEquality(out_wmma_accumulator_shared_ax2, [out_wmma_accumulator_shared_ax2_outer, out_wmma_accumulator_shared_ax2_inner])
model.Add(out_wmma_accumulator_shared_ax2_outer == out_wmma_accumulator_sharedax2tileSpatial)
model.AddMultiplicationEquality(out_wmma_accumulator_shared_ax3, [out_wmma_accumulator_shared_ax3_outer, out_wmma_accumulator_shared_ax3_inner])
model.Add(out_wmma_accumulator_shared_ax3_outer == out_wmma_accumulator_sharedax3tileSpatial)
model.AddMultiplicationEquality(out_wmma_accumulator_sharedax0tileSpatial_out_wmma_accumulator_sharedax1tileSpatial, [out_wmma_accumulator_sharedax0tileSpatial, out_wmma_accumulator_sharedax1tileSpatial])
model.AddMultiplicationEquality(out_wmma_accumulator_sharedax0tileSpatial_out_wmma_accumulator_sharedax1tileSpatial_out_wmma_accumulator_sharedax2tileSpatial, [out_wmma_accumulator_sharedax0tileSpatial_out_wmma_accumulator_sharedax1tileSpatial, out_wmma_accumulator_sharedax2tileSpatial])
model.AddMultiplicationEquality(threadIdx_y, [out_wmma_accumulator_sharedax0tileSpatial_out_wmma_accumulator_sharedax1tileSpatial_out_wmma_accumulator_sharedax2tileSpatial, out_wmma_accumulator_sharedax3tileSpatial])
model.AddMultiplicationEquality(out_wmma_accumulator_shared_ax0_outer_out_wmma_accumulator_shared_ax1_outer, [out_wmma_accumulator_shared_ax0_outer, out_wmma_accumulator_shared_ax1_outer])
model.AddMultiplicationEquality(out_wmma_accumulator_shared_ax0_outer_out_wmma_accumulator_shared_ax1_outer_out_wmma_accumulator_shared_ax2_outer, [out_wmma_accumulator_shared_ax0_outer_out_wmma_accumulator_shared_ax1_outer, out_wmma_accumulator_shared_ax2_outer])
model.AddMultiplicationEquality(out_wmma_accumulator_shared_ax0_outer_ax1_outer_fused_ax2_outer_fused_ax3_outer_fused, [out_wmma_accumulator_shared_ax0_outer_out_wmma_accumulator_shared_ax1_outer_out_wmma_accumulator_shared_ax2_outer, out_wmma_accumulator_shared_ax3_outer])
model.AddMultiplicationEquality(out_wmma_accumulator_shared_ax0_inner, [out_wmma_accumulator_shared_ax0_inner_outer, out_wmma_accumulator_shared_ax0_inner_inner])
model.Add(out_wmma_accumulator_shared_ax0_inner_inner == wmma_m)
model.AddMultiplicationEquality(out_wmma_accumulator_shared_ax1_inner, [out_wmma_accumulator_shared_ax1_inner_outer, out_wmma_accumulator_shared_ax1_inner_inner])
model.Add(out_wmma_accumulator_shared_ax1_inner_inner == 1)
model.AddMultiplicationEquality(out_wmma_accumulator_shared_ax2_inner, [out_wmma_accumulator_shared_ax2_inner_outer, out_wmma_accumulator_shared_ax2_inner_inner])
model.Add(out_wmma_accumulator_shared_ax2_inner_inner == 1)
model.AddMultiplicationEquality(out_wmma_accumulator_shared_ax3_inner, [out_wmma_accumulator_shared_ax3_inner_outer, out_wmma_accumulator_shared_ax3_inner_inner])
model.Add(out_wmma_accumulator_shared_ax3_inner_inner == wmma_n)
model.Add(out_wmma_accumulator_nn_c == out_wmma_accumulator_shared_ax0_inner).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select0)
model.Add(out_wmma_accumulator_shared_local_pos == 0).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select0)
model.Add(out_wmma_accumulator_nn_c == out_wmma_accumulator_shared_ax0_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select1)
model.Add(out_wmma_accumulator_shared_local_pos == 1).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select1)
model.Add(sum([out_wmma_accumulator_shared_local_pos_select0, out_wmma_accumulator_shared_local_pos_select1]) == 1)
model.Add(out_wmma_accumulator_yy_c == out_wmma_accumulator_shared_ax1_inner).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select0)
model.Add(out_wmma_accumulator_shared_local_pos == 0).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select0)
model.Add(out_wmma_accumulator_yy_c == out_wmma_accumulator_shared_ax1_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select1)
model.Add(out_wmma_accumulator_shared_local_pos == 1).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select1)
model.Add(sum([out_wmma_accumulator_shared_local_pos_select0, out_wmma_accumulator_shared_local_pos_select1]) == 1)
model.Add(out_wmma_accumulator_xx_c == out_wmma_accumulator_shared_ax2_inner).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select0)
model.Add(out_wmma_accumulator_shared_local_pos == 0).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select0)
model.Add(out_wmma_accumulator_xx_c == out_wmma_accumulator_shared_ax2_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select1)
model.Add(out_wmma_accumulator_shared_local_pos == 1).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select1)
model.Add(sum([out_wmma_accumulator_shared_local_pos_select0, out_wmma_accumulator_shared_local_pos_select1]) == 1)
model.Add(out_wmma_accumulator_ff_c == out_wmma_accumulator_shared_ax3_inner).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select0)
model.Add(out_wmma_accumulator_shared_local_pos == 0).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select0)
model.Add(out_wmma_accumulator_ff_c == out_wmma_accumulator_shared_ax3_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select1)
model.Add(out_wmma_accumulator_shared_local_pos == 1).OnlyEnforceIf(out_wmma_accumulator_shared_local_pos_select1)
model.Add(sum([out_wmma_accumulator_shared_local_pos_select0, out_wmma_accumulator_shared_local_pos_select1]) == 1)
model.AddMultiplicationEquality(out_wmma_accumulator_nn_c, [out_wmma_accumulator_nn_c_outer, out_wmma_accumulator_nn_c_inner])
model.Add(out_wmma_accumulator_nn_c_outer == out_wmma_accumulatornn_ctileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_yy_c, [out_wmma_accumulator_yy_c_outer, out_wmma_accumulator_yy_c_inner])
model.Add(out_wmma_accumulator_yy_c_outer == out_wmma_accumulatoryy_ctileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_xx_c, [out_wmma_accumulator_xx_c_outer, out_wmma_accumulator_xx_c_inner])
model.Add(out_wmma_accumulator_xx_c_outer == out_wmma_accumulatorxx_ctileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_ff_c, [out_wmma_accumulator_ff_c_outer, out_wmma_accumulator_ff_c_inner])
model.Add(out_wmma_accumulator_ff_c_outer == out_wmma_accumulatorff_ctileAll)
model.AddMultiplicationEquality(1, [out_wmma_accumulator_ry_outer, out_wmma_accumulator_ry_inner])
model.Add(out_wmma_accumulator_ry_outer == out_wmma_accumulatorrytileAll)
model.AddMultiplicationEquality(1, [out_wmma_accumulator_rx_outer, out_wmma_accumulator_rx_inner])
model.Add(out_wmma_accumulator_rx_outer == out_wmma_accumulatorrxtileAll)
model.AddMultiplicationEquality(128, [out_wmma_accumulator_rc_outer, out_wmma_accumulator_rc_inner])
model.Add(out_wmma_accumulator_rc_outer == out_wmma_accumulatorrctileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_nn_c_inner, [out_wmma_accumulator_nn_c_inner_outer, out_wmma_accumulator_nn_c_inner_inner])
model.Add(out_wmma_accumulator_nn_c_inner_outer == out_wmma_accumulatornn_c_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_yy_c_inner, [out_wmma_accumulator_yy_c_inner_outer, out_wmma_accumulator_yy_c_inner_inner])
model.Add(out_wmma_accumulator_yy_c_inner_outer == out_wmma_accumulatoryy_c_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_xx_c_inner, [out_wmma_accumulator_xx_c_inner_outer, out_wmma_accumulator_xx_c_inner_inner])
model.Add(out_wmma_accumulator_xx_c_inner_outer == out_wmma_accumulatorxx_c_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_ff_c_inner, [out_wmma_accumulator_ff_c_inner_outer, out_wmma_accumulator_ff_c_inner_inner])
model.Add(out_wmma_accumulator_ff_c_inner_outer == out_wmma_accumulatorff_c_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_ry_inner, [out_wmma_accumulator_ry_inner_outer, out_wmma_accumulator_ry_inner_inner])
model.Add(out_wmma_accumulator_ry_inner_outer == out_wmma_accumulatorry_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_rx_inner, [out_wmma_accumulator_rx_inner_outer, out_wmma_accumulator_rx_inner_inner])
model.Add(out_wmma_accumulator_rx_inner_outer == out_wmma_accumulatorrx_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_rc_inner, [out_wmma_accumulator_rc_inner_outer, out_wmma_accumulator_rc_inner_inner])
model.Add(out_wmma_accumulator_rc_inner_outer == out_wmma_accumulatorrc_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_nn_c_inner_inner, [out_wmma_accumulator_nn_c_inner_inner_outer, out_wmma_accumulator_nn_c_inner_inner_inner])
model.Add(out_wmma_accumulator_nn_c_inner_inner_outer == out_wmma_accumulatornn_c_inner_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_yy_c_inner_inner, [out_wmma_accumulator_yy_c_inner_inner_outer, out_wmma_accumulator_yy_c_inner_inner_inner])
model.Add(out_wmma_accumulator_yy_c_inner_inner_outer == out_wmma_accumulatoryy_c_inner_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_xx_c_inner_inner, [out_wmma_accumulator_xx_c_inner_inner_outer, out_wmma_accumulator_xx_c_inner_inner_inner])
model.Add(out_wmma_accumulator_xx_c_inner_inner_outer == out_wmma_accumulatorxx_c_inner_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_ff_c_inner_inner, [out_wmma_accumulator_ff_c_inner_inner_outer, out_wmma_accumulator_ff_c_inner_inner_inner])
model.Add(out_wmma_accumulator_ff_c_inner_inner_outer == out_wmma_accumulatorff_c_inner_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_ry_inner_inner, [out_wmma_accumulator_ry_inner_inner_outer, out_wmma_accumulator_ry_inner_inner_inner])
model.Add(out_wmma_accumulator_ry_inner_inner_outer == out_wmma_accumulatorry_inner_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_rx_inner_inner, [out_wmma_accumulator_rx_inner_inner_outer, out_wmma_accumulator_rx_inner_inner_inner])
model.Add(out_wmma_accumulator_rx_inner_inner_outer == out_wmma_accumulatorrx_inner_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_rc_inner_inner, [out_wmma_accumulator_rc_inner_inner_outer, out_wmma_accumulator_rc_inner_inner_inner])
model.Add(out_wmma_accumulator_rc_inner_inner_outer == out_wmma_accumulatorrc_inner_innertileAll)
model.AddMultiplicationEquality(out_wmma_accumulator_nn_c_inner_inner_inner, [out_wmma_accumulator_nn_c_inner_inner_inner_outer, out_wmma_accumulator_nn_c_inner_inner_inner_inner])
model.Add(out_wmma_accumulator_nn_c_inner_inner_inner_inner == wmma_m)
model.AddMultiplicationEquality(out_wmma_accumulator_yy_c_inner_inner_inner, [out_wmma_accumulator_yy_c_inner_inner_inner_outer, out_wmma_accumulator_yy_c_inner_inner_inner_inner])
model.Add(out_wmma_accumulator_yy_c_inner_inner_inner_inner == 1)
model.AddMultiplicationEquality(out_wmma_accumulator_xx_c_inner_inner_inner, [out_wmma_accumulator_xx_c_inner_inner_inner_outer, out_wmma_accumulator_xx_c_inner_inner_inner_inner])
model.Add(out_wmma_accumulator_xx_c_inner_inner_inner_inner == 1)
model.AddMultiplicationEquality(out_wmma_accumulator_ff_c_inner_inner_inner, [out_wmma_accumulator_ff_c_inner_inner_inner_outer, out_wmma_accumulator_ff_c_inner_inner_inner_inner])
model.Add(out_wmma_accumulator_ff_c_inner_inner_inner_inner == wmma_n)
model.AddMultiplicationEquality(out_wmma_accumulator_ry_inner_inner_inner, [out_wmma_accumulator_ry_inner_inner_inner_outer, out_wmma_accumulator_ry_inner_inner_inner_inner])
model.Add(out_wmma_accumulator_ry_inner_inner_inner_inner == 1)
model.AddMultiplicationEquality(out_wmma_accumulator_rx_inner_inner_inner, [out_wmma_accumulator_rx_inner_inner_inner_outer, out_wmma_accumulator_rx_inner_inner_inner_inner])
model.Add(out_wmma_accumulator_rx_inner_inner_inner_inner == 1)
model.AddMultiplicationEquality(out_wmma_accumulator_rc_inner_inner_inner, [out_wmma_accumulator_rc_inner_inner_inner_outer, out_wmma_accumulator_rc_inner_inner_inner_inner])
model.Add(out_wmma_accumulator_rc_inner_inner_inner_inner == wmma_k)
model.Add(out_wmma_accumulator_shared_pos <= out_wmma_accumulator_local_pos)
model.Add(filter_shared_wmma_matrix_b_ax0 == out_wmma_accumulator_ry_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(out_wmma_accumulator_local_pos == 0).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(filter_shared_wmma_matrix_b_ax0 == out_wmma_accumulator_ry_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(out_wmma_accumulator_local_pos == 1).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(filter_shared_wmma_matrix_b_ax0 == out_wmma_accumulator_ry_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(out_wmma_accumulator_local_pos == 2).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(filter_shared_wmma_matrix_b_ax0 == out_wmma_accumulator_ry_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(out_wmma_accumulator_local_pos == 3).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(sum([out_wmma_accumulator_local_pos_select0, out_wmma_accumulator_local_pos_select1, out_wmma_accumulator_local_pos_select2, out_wmma_accumulator_local_pos_select3]) == 1)
model.Add(filter_shared_wmma_matrix_b_ax1 == out_wmma_accumulator_rx_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(out_wmma_accumulator_local_pos == 0).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(filter_shared_wmma_matrix_b_ax1 == out_wmma_accumulator_rx_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(out_wmma_accumulator_local_pos == 1).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(filter_shared_wmma_matrix_b_ax1 == out_wmma_accumulator_rx_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(out_wmma_accumulator_local_pos == 2).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(filter_shared_wmma_matrix_b_ax1 == out_wmma_accumulator_rx_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(out_wmma_accumulator_local_pos == 3).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(sum([out_wmma_accumulator_local_pos_select0, out_wmma_accumulator_local_pos_select1, out_wmma_accumulator_local_pos_select2, out_wmma_accumulator_local_pos_select3]) == 1)
model.Add(filter_shared_wmma_matrix_b_ax2 == out_wmma_accumulator_rc_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(out_wmma_accumulator_local_pos == 0).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(filter_shared_wmma_matrix_b_ax2 == out_wmma_accumulator_rc_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(out_wmma_accumulator_local_pos == 1).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(filter_shared_wmma_matrix_b_ax2 == out_wmma_accumulator_rc_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(out_wmma_accumulator_local_pos == 2).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(filter_shared_wmma_matrix_b_ax2 == out_wmma_accumulator_rc_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(out_wmma_accumulator_local_pos == 3).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(sum([out_wmma_accumulator_local_pos_select0, out_wmma_accumulator_local_pos_select1, out_wmma_accumulator_local_pos_select2, out_wmma_accumulator_local_pos_select3]) == 1)
model.Add(filter_shared_wmma_matrix_b_ax3 == out_wmma_accumulator_ff_c_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(out_wmma_accumulator_local_pos == 0).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(filter_shared_wmma_matrix_b_ax3 == out_wmma_accumulator_ff_c_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(out_wmma_accumulator_local_pos == 1).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(filter_shared_wmma_matrix_b_ax3 == out_wmma_accumulator_ff_c_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(out_wmma_accumulator_local_pos == 2).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(filter_shared_wmma_matrix_b_ax3 == out_wmma_accumulator_ff_c_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(out_wmma_accumulator_local_pos == 3).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(sum([out_wmma_accumulator_local_pos_select0, out_wmma_accumulator_local_pos_select1, out_wmma_accumulator_local_pos_select2, out_wmma_accumulator_local_pos_select3]) == 1)
model.AddMultiplicationEquality(filter_shared_wmma_matrix_b_ax0, [filter_shared_wmma_matrix_b_ax0_outer, filter_shared_wmma_matrix_b_ax0_inner])
model.Add(filter_shared_wmma_matrix_b_ax0_inner == 1)
model.AddMultiplicationEquality(filter_shared_wmma_matrix_b_ax1, [filter_shared_wmma_matrix_b_ax1_outer, filter_shared_wmma_matrix_b_ax1_inner])
model.Add(filter_shared_wmma_matrix_b_ax1_inner == 1)
model.AddMultiplicationEquality(filter_shared_wmma_matrix_b_ax2, [filter_shared_wmma_matrix_b_ax2_outer, filter_shared_wmma_matrix_b_ax2_inner])
model.Add(filter_shared_wmma_matrix_b_ax2_inner == wmma_k)
model.AddMultiplicationEquality(filter_shared_wmma_matrix_b_ax3, [filter_shared_wmma_matrix_b_ax3_outer, filter_shared_wmma_matrix_b_ax3_inner])
model.Add(filter_shared_wmma_matrix_b_ax3_inner == wmma_n)
model.Add(filter_shared_ax0 == out_wmma_accumulator_ry_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(out_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(filter_shared_ax0 == out_wmma_accumulator_ry_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(out_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(filter_shared_ax0 == out_wmma_accumulator_ry_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(out_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(filter_shared_ax0 == out_wmma_accumulator_ry_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(out_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(sum([out_wmma_accumulator_shared_pos_select0, out_wmma_accumulator_shared_pos_select1, out_wmma_accumulator_shared_pos_select2, out_wmma_accumulator_shared_pos_select3]) == 1)
model.Add(filter_shared_ax1 == out_wmma_accumulator_rx_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(out_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(filter_shared_ax1 == out_wmma_accumulator_rx_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(out_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(filter_shared_ax1 == out_wmma_accumulator_rx_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(out_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(filter_shared_ax1 == out_wmma_accumulator_rx_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(out_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(sum([out_wmma_accumulator_shared_pos_select0, out_wmma_accumulator_shared_pos_select1, out_wmma_accumulator_shared_pos_select2, out_wmma_accumulator_shared_pos_select3]) == 1)
model.Add(filter_shared_ax2 == out_wmma_accumulator_rc_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(out_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(filter_shared_ax2 == out_wmma_accumulator_rc_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(out_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(filter_shared_ax2 == out_wmma_accumulator_rc_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(out_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(filter_shared_ax2 == out_wmma_accumulator_rc_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(out_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(sum([out_wmma_accumulator_shared_pos_select0, out_wmma_accumulator_shared_pos_select1, out_wmma_accumulator_shared_pos_select2, out_wmma_accumulator_shared_pos_select3]) == 1)
model.Add(filter_shared_tmp_ax3 == out_wmma_accumulator_ff_c_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(out_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(filter_shared_tmp_ax3 == out_wmma_accumulator_ff_c_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(out_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(filter_shared_tmp_ax3 == out_wmma_accumulator_ff_c_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(out_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(filter_shared_tmp_ax3 == out_wmma_accumulator_ff_c_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(out_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(sum([out_wmma_accumulator_shared_pos_select0, out_wmma_accumulator_shared_pos_select1, out_wmma_accumulator_shared_pos_select2, out_wmma_accumulator_shared_pos_select3]) == 1)
model.AddMultiplicationEquality(filter_shared_ax3, [filter_shared_tmp_ax3, out_wmma_accumulator_sharedax3tileSpatial])
model.Add(filter_shared_offset == 0).OnlyEnforceIf(filter_shared_offset_cand0)
model.Add(filter_shared_offset == 8).OnlyEnforceIf(filter_shared_offset_cand1)
model.Add(filter_shared_offset == 16).OnlyEnforceIf(filter_shared_offset_cand2)
model.Add(filter_shared_offset == 24).OnlyEnforceIf(filter_shared_offset_cand3)
model.Add(filter_shared_offset == 32).OnlyEnforceIf(filter_shared_offset_cand4)
model.Add(filter_shared_offset == 48).OnlyEnforceIf(filter_shared_offset_cand5)
model.Add(sum([filter_shared_offset_cand0, filter_shared_offset_cand1, filter_shared_offset_cand2, filter_shared_offset_cand3, filter_shared_offset_cand4, filter_shared_offset_cand5]) == 1)
model.Add(sum([filter_shared_ax3, filter_shared_offset]) == filter_shared_align_size)
model.AddMultiplicationEquality(filter_shared_ax0_filter_shared_ax1, [filter_shared_ax0, filter_shared_ax1])
model.AddMultiplicationEquality(filter_shared_ax0_filter_shared_ax1_filter_shared_ax2, [filter_shared_ax0_filter_shared_ax1, filter_shared_ax2])
model.AddMultiplicationEquality(filter_shared_ax0_ax1_fused_ax2_fused_ax3_fused, [filter_shared_ax0_filter_shared_ax1_filter_shared_ax2, filter_shared_ax3])
model.Add(filter_shared_vectorize == 1).OnlyEnforceIf(filter_shared_vectorize_cand0)
model.Add(filter_shared_vectorize == 2).OnlyEnforceIf(filter_shared_vectorize_cand1)
model.Add(filter_shared_vectorize == 4).OnlyEnforceIf(filter_shared_vectorize_cand2)
model.Add(filter_shared_vectorize == 8).OnlyEnforceIf(filter_shared_vectorize_cand3)
model.Add(sum([filter_shared_vectorize_cand0, filter_shared_vectorize_cand1, filter_shared_vectorize_cand2, filter_shared_vectorize_cand3]) == 1)
model.Add(PaddedInput_shared_wmma_matrix_a_ax0 == out_wmma_accumulator_nn_c_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(out_wmma_accumulator_local_pos == 0).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(PaddedInput_shared_wmma_matrix_a_ax0 == out_wmma_accumulator_nn_c_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(out_wmma_accumulator_local_pos == 1).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(PaddedInput_shared_wmma_matrix_a_ax0 == out_wmma_accumulator_nn_c_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(out_wmma_accumulator_local_pos == 2).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(PaddedInput_shared_wmma_matrix_a_ax0 == out_wmma_accumulator_nn_c_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(out_wmma_accumulator_local_pos == 3).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(sum([out_wmma_accumulator_local_pos_select0, out_wmma_accumulator_local_pos_select1, out_wmma_accumulator_local_pos_select2, out_wmma_accumulator_local_pos_select3]) == 1)
model.Add(PaddedInput_shared_wmma_matrix_a_ax1 == out_wmma_accumulator_yy_c_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(out_wmma_accumulator_local_pos == 0).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(PaddedInput_shared_wmma_matrix_a_ax1 == out_wmma_accumulator_yy_c_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(out_wmma_accumulator_local_pos == 1).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(PaddedInput_shared_wmma_matrix_a_ax1 == out_wmma_accumulator_yy_c_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(out_wmma_accumulator_local_pos == 2).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(PaddedInput_shared_wmma_matrix_a_ax1 == out_wmma_accumulator_yy_c_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(out_wmma_accumulator_local_pos == 3).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(sum([out_wmma_accumulator_local_pos_select0, out_wmma_accumulator_local_pos_select1, out_wmma_accumulator_local_pos_select2, out_wmma_accumulator_local_pos_select3]) == 1)
model.Add(PaddedInput_shared_wmma_matrix_a_ax2 == out_wmma_accumulator_xx_c_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(out_wmma_accumulator_local_pos == 0).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(PaddedInput_shared_wmma_matrix_a_ax2 == out_wmma_accumulator_xx_c_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(out_wmma_accumulator_local_pos == 1).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(PaddedInput_shared_wmma_matrix_a_ax2 == out_wmma_accumulator_xx_c_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(out_wmma_accumulator_local_pos == 2).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(PaddedInput_shared_wmma_matrix_a_ax2 == out_wmma_accumulator_xx_c_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(out_wmma_accumulator_local_pos == 3).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(sum([out_wmma_accumulator_local_pos_select0, out_wmma_accumulator_local_pos_select1, out_wmma_accumulator_local_pos_select2, out_wmma_accumulator_local_pos_select3]) == 1)
model.Add(PaddedInput_shared_wmma_matrix_a_ax3 == out_wmma_accumulator_rc_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(out_wmma_accumulator_local_pos == 0).OnlyEnforceIf(out_wmma_accumulator_local_pos_select0)
model.Add(PaddedInput_shared_wmma_matrix_a_ax3 == out_wmma_accumulator_rc_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(out_wmma_accumulator_local_pos == 1).OnlyEnforceIf(out_wmma_accumulator_local_pos_select1)
model.Add(PaddedInput_shared_wmma_matrix_a_ax3 == out_wmma_accumulator_rc_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(out_wmma_accumulator_local_pos == 2).OnlyEnforceIf(out_wmma_accumulator_local_pos_select2)
model.Add(PaddedInput_shared_wmma_matrix_a_ax3 == out_wmma_accumulator_rc_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(out_wmma_accumulator_local_pos == 3).OnlyEnforceIf(out_wmma_accumulator_local_pos_select3)
model.Add(sum([out_wmma_accumulator_local_pos_select0, out_wmma_accumulator_local_pos_select1, out_wmma_accumulator_local_pos_select2, out_wmma_accumulator_local_pos_select3]) == 1)
model.AddMultiplicationEquality(PaddedInput_shared_wmma_matrix_a_ax0, [PaddedInput_shared_wmma_matrix_a_ax0_outer, PaddedInput_shared_wmma_matrix_a_ax0_inner])
model.Add(PaddedInput_shared_wmma_matrix_a_ax0_inner == wmma_m)
model.AddMultiplicationEquality(PaddedInput_shared_wmma_matrix_a_ax1, [PaddedInput_shared_wmma_matrix_a_ax1_outer, PaddedInput_shared_wmma_matrix_a_ax1_inner])
model.Add(PaddedInput_shared_wmma_matrix_a_ax1_inner == 1)
model.AddMultiplicationEquality(PaddedInput_shared_wmma_matrix_a_ax2, [PaddedInput_shared_wmma_matrix_a_ax2_outer, PaddedInput_shared_wmma_matrix_a_ax2_inner])
model.Add(PaddedInput_shared_wmma_matrix_a_ax2_inner == 1)
model.AddMultiplicationEquality(PaddedInput_shared_wmma_matrix_a_ax3, [PaddedInput_shared_wmma_matrix_a_ax3_outer, PaddedInput_shared_wmma_matrix_a_ax3_inner])
model.Add(PaddedInput_shared_wmma_matrix_a_ax3_inner == wmma_k)
model.Add(PaddedInput_shared_tmp_ax0 == out_wmma_accumulator_nn_c_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(out_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(PaddedInput_shared_tmp_ax0 == out_wmma_accumulator_nn_c_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(out_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(PaddedInput_shared_tmp_ax0 == out_wmma_accumulator_nn_c_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(out_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(PaddedInput_shared_tmp_ax0 == out_wmma_accumulator_nn_c_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(out_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(sum([out_wmma_accumulator_shared_pos_select0, out_wmma_accumulator_shared_pos_select1, out_wmma_accumulator_shared_pos_select2, out_wmma_accumulator_shared_pos_select3]) == 1)
model.AddMultiplicationEquality(PaddedInput_shared_ax0, [PaddedInput_shared_tmp_ax0, out_wmma_accumulator_sharedax0tileSpatial])
model.Add(PaddedInput_shared_tmp_ax1 == out_wmma_accumulator_yy_c_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(out_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(PaddedInput_shared_tmp_ax1 == out_wmma_accumulator_yy_c_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(out_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(PaddedInput_shared_tmp_ax1 == out_wmma_accumulator_yy_c_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(out_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(PaddedInput_shared_tmp_ax1 == out_wmma_accumulator_yy_c_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(out_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(sum([out_wmma_accumulator_shared_pos_select0, out_wmma_accumulator_shared_pos_select1, out_wmma_accumulator_shared_pos_select2, out_wmma_accumulator_shared_pos_select3]) == 1)
model.AddMultiplicationEquality(PaddedInput_shared_ax1, [PaddedInput_shared_tmp_ax1, out_wmma_accumulator_sharedax1tileSpatial])
model.Add(PaddedInput_shared_tmp_ax2 == out_wmma_accumulator_xx_c_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(out_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(PaddedInput_shared_tmp_ax2 == out_wmma_accumulator_xx_c_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(out_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(PaddedInput_shared_tmp_ax2 == out_wmma_accumulator_xx_c_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(out_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(PaddedInput_shared_tmp_ax2 == out_wmma_accumulator_xx_c_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(out_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(sum([out_wmma_accumulator_shared_pos_select0, out_wmma_accumulator_shared_pos_select1, out_wmma_accumulator_shared_pos_select2, out_wmma_accumulator_shared_pos_select3]) == 1)
model.AddMultiplicationEquality(PaddedInput_shared_ax2, [PaddedInput_shared_tmp_ax2, out_wmma_accumulator_sharedax2tileSpatial])
model.Add(PaddedInput_shared_ax3 == out_wmma_accumulator_rc_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(out_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select0)
model.Add(PaddedInput_shared_ax3 == out_wmma_accumulator_rc_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(out_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select1)
model.Add(PaddedInput_shared_ax3 == out_wmma_accumulator_rc_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(out_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select2)
model.Add(PaddedInput_shared_ax3 == out_wmma_accumulator_rc_inner_inner_inner_inner).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(out_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(out_wmma_accumulator_shared_pos_select3)
model.Add(sum([out_wmma_accumulator_shared_pos_select0, out_wmma_accumulator_shared_pos_select1, out_wmma_accumulator_shared_pos_select2, out_wmma_accumulator_shared_pos_select3]) == 1)
model.Add(PaddedInput_shared_offset == 0).OnlyEnforceIf(PaddedInput_shared_offset_cand0)
model.Add(PaddedInput_shared_offset == 8).OnlyEnforceIf(PaddedInput_shared_offset_cand1)
model.Add(PaddedInput_shared_offset == 16).OnlyEnforceIf(PaddedInput_shared_offset_cand2)
model.Add(PaddedInput_shared_offset == 24).OnlyEnforceIf(PaddedInput_shared_offset_cand3)
model.Add(PaddedInput_shared_offset == 32).OnlyEnforceIf(PaddedInput_shared_offset_cand4)
model.Add(PaddedInput_shared_offset == 48).OnlyEnforceIf(PaddedInput_shared_offset_cand5)
model.Add(sum([PaddedInput_shared_offset_cand0, PaddedInput_shared_offset_cand1, PaddedInput_shared_offset_cand2, PaddedInput_shared_offset_cand3, PaddedInput_shared_offset_cand4, PaddedInput_shared_offset_cand5]) == 1)
model.Add(sum([PaddedInput_shared_ax3, PaddedInput_shared_offset]) == PaddedInput_shared_align_size)
model.AddMultiplicationEquality(PaddedInput_shared_ax0_PaddedInput_shared_ax1, [PaddedInput_shared_ax0, PaddedInput_shared_ax1])
model.AddMultiplicationEquality(PaddedInput_shared_ax0_PaddedInput_shared_ax1_PaddedInput_shared_ax2, [PaddedInput_shared_ax0_PaddedInput_shared_ax1, PaddedInput_shared_ax2])
model.AddMultiplicationEquality(PaddedInput_shared_ax0_ax1_fused_ax2_fused_ax3_fused, [PaddedInput_shared_ax0_PaddedInput_shared_ax1_PaddedInput_shared_ax2, PaddedInput_shared_ax3])
model.Add(PaddedInput_shared_vectorize == 1).OnlyEnforceIf(PaddedInput_shared_vectorize_cand0)
model.Add(PaddedInput_shared_vectorize == 2).OnlyEnforceIf(PaddedInput_shared_vectorize_cand1)
model.Add(PaddedInput_shared_vectorize == 4).OnlyEnforceIf(PaddedInput_shared_vectorize_cand2)
model.Add(PaddedInput_shared_vectorize == 8).OnlyEnforceIf(PaddedInput_shared_vectorize_cand3)
model.Add(sum([PaddedInput_shared_vectorize_cand0, PaddedInput_shared_vectorize_cand1, PaddedInput_shared_vectorize_cand2, PaddedInput_shared_vectorize_cand3]) == 1)
model.AddMultiplicationEquality(threads, [threadIdx_x, threadIdx_y])
model.AddMultiplicationEquality(PaddedInput_shared_ax0_PaddedInput_shared_ax1, [PaddedInput_shared_ax0, PaddedInput_shared_ax1])
model.AddMultiplicationEquality(PaddedInput_shared_ax0_PaddedInput_shared_ax1_PaddedInput_shared_ax2, [PaddedInput_shared_ax0_PaddedInput_shared_ax1, PaddedInput_shared_ax2])
model.AddMultiplicationEquality(PaddedInput_shared_shared_mem_size, [PaddedInput_shared_ax0_PaddedInput_shared_ax1_PaddedInput_shared_ax2, PaddedInput_shared_align_size])
model.AddMultiplicationEquality(filter_shared_ax0_filter_shared_ax1, [filter_shared_ax0, filter_shared_ax1])
model.AddMultiplicationEquality(filter_shared_ax0_filter_shared_ax1_filter_shared_ax2, [filter_shared_ax0_filter_shared_ax1, filter_shared_ax2])
model.AddMultiplicationEquality(filter_shared_shared_mem_size, [filter_shared_ax0_filter_shared_ax1_filter_shared_ax2, filter_shared_align_size])
model.AddMultiplicationEquality(out_wmma_accumulator_shared_ax0_out_wmma_accumulator_shared_ax1, [out_wmma_accumulator_shared_ax0, out_wmma_accumulator_shared_ax1])
model.AddMultiplicationEquality(out_wmma_accumulator_shared_ax0_out_wmma_accumulator_shared_ax1_out_wmma_accumulator_shared_ax2, [out_wmma_accumulator_shared_ax0_out_wmma_accumulator_shared_ax1, out_wmma_accumulator_shared_ax2])
model.AddMultiplicationEquality(out_wmma_accumulator_shared_shared_mem_size, [out_wmma_accumulator_shared_ax0_out_wmma_accumulator_shared_ax1_out_wmma_accumulator_shared_ax2, out_wmma_accumulator_shared_align_size])
solver = cp_model.CpSolver()
status = solver.Solve(model)
