from ortools.sat.python import cp_model

model = cp_model.CpModel()
wmma_m = model.NewIntVar(8, 32, 'wmma_m')
wmma_m_cand0 = model.NewIntVar(0, 1, 'wmma_m_cand0')
wmma_m_cand1 = model.NewIntVar(0, 1, 'wmma_m_cand1')
wmma_m_cand2 = model.NewIntVar(0, 1, 'wmma_m_cand2')
wmma_k = model.NewIntVar(16, 16, 'wmma_k')
wmma_n = model.NewIntVar(8, 32, 'wmma_n')
wmma_n_cand0 = model.NewIntVar(0, 1, 'wmma_n_cand0')
wmma_n_cand1 = model.NewIntVar(0, 1, 'wmma_n_cand1')
wmma_n_cand2 = model.NewIntVar(0, 1, 'wmma_n_cand2')
wmma_m_wmma_n = model.NewIntVar(1, 4096, 'wmma_m_wmma_n')
batch_matmul_wmma_accumulator_shared_pos = model.NewIntVar(0, 3, 'batch_matmul_wmma_accumulator_shared_pos')
batch_matmul_wmma_accumulator_local_pos = model.NewIntVar(0, 3, 'batch_matmul_wmma_accumulator_local_pos')
batch_matmul_shared_pos = model.NewIntVar(1, 5, 'batch_matmul_shared_pos')
batch_matmul_wmma_accumulator_shared_local_pos = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_shared_local_pos')
batch_matmul_unroll_pragma = model.NewIntVar(0, 5, 'batch_matmul_unroll_pragma')
batch_matmul_b_outer = model.NewIntVar(1, 96, 'batch_matmul_b_outer')
batch_matmul_b_inner = model.NewIntVar(1, 96, 'batch_matmul_b_inner')
batch_matmul_i_outer = model.NewIntVar(1, 2048, 'batch_matmul_i_outer')
batch_matmul_i_inner = model.NewIntVar(1, 2048, 'batch_matmul_i_inner')
batch_matmul_j_outer = model.NewIntVar(1, 2048, 'batch_matmul_j_outer')
batch_matmul_j_inner = model.NewIntVar(1, 2048, 'batch_matmul_j_inner')
batch_matmulb_innertileSpatial = model.NewIntVar(96, 96, 'batch_matmulb_innertileSpatial')
batch_matmul_b_inner_outer = model.NewIntVar(1, 96, 'batch_matmul_b_inner_outer')
batch_matmul_b_inner_inner = model.NewIntVar(1, 96, 'batch_matmul_b_inner_inner')
batch_matmuli_innertileSpatial = model.NewIntVar(1, 2048, 'batch_matmuli_innertileSpatial')
batch_matmul_i_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_i_inner_outer')
batch_matmul_i_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_i_inner_inner')
batch_matmulj_innertileSpatial = model.NewIntVar(1, 2048, 'batch_matmulj_innertileSpatial')
batch_matmul_j_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_j_inner_outer')
batch_matmul_j_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_j_inner_inner')
blockIdx_x = model.NewIntVar(1, 8888888, 'blockIdx_x')
batch_matmulb_innertileSpatial_batch_matmuli_innertileSpatial = model.NewIntVar(1, 8888888, 'batch_matmulb_innertileSpatial_batch_matmuli_innertileSpatial')
batch_matmul_b_inner_outer_i_inner_outer_fused_j_inner_outer_fused = model.NewIntVar(1, 1000000, 'batch_matmul_b_inner_outer_i_inner_outer_fused_j_inner_outer_fused')
batch_matmul_b_inner_outer_batch_matmul_i_inner_outer = model.NewIntVar(1, 1000000, 'batch_matmul_b_inner_outer_batch_matmul_i_inner_outer')
batch_matmulb_inner_innertileSpatial = model.NewIntVar(1, 96, 'batch_matmulb_inner_innertileSpatial')
batch_matmul_b_inner_inner_outer = model.NewIntVar(1, 96, 'batch_matmul_b_inner_inner_outer')
batch_matmul_b_inner_inner_inner = model.NewIntVar(1, 96, 'batch_matmul_b_inner_inner_inner')
batch_matmuli_inner_innertileSpatial = model.NewIntVar(1, 2048, 'batch_matmuli_inner_innertileSpatial')
batch_matmul_i_inner_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_i_inner_inner_outer')
batch_matmul_i_inner_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_i_inner_inner_inner')
batch_matmulj_inner_innertileSpatial = model.NewIntVar(1, 2048, 'batch_matmulj_inner_innertileSpatial')
batch_matmul_j_inner_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_j_inner_inner_outer')
batch_matmul_j_inner_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_j_inner_inner_inner')
threadIdx_y = model.NewIntVar(1, 1024, 'threadIdx_y')
batch_matmulb_inner_innertileSpatial_batch_matmuli_inner_innertileSpatial = model.NewIntVar(1, 1024, 'batch_matmulb_inner_innertileSpatial_batch_matmuli_inner_innertileSpatial')
batch_matmul_b_inner_inner_outer_i_inner_inner_outer_fused_j_inner_inner_outer_fused = model.NewIntVar(1, 1000000, 'batch_matmul_b_inner_inner_outer_i_inner_inner_outer_fused_j_inner_inner_outer_fused')
batch_matmul_b_inner_inner_outer_batch_matmul_i_inner_inner_outer = model.NewIntVar(1, 1000000, 'batch_matmul_b_inner_inner_outer_batch_matmul_i_inner_inner_outer')
batch_matmulb_inner_inner_innertileSpatial = model.NewIntVar(1, 96, 'batch_matmulb_inner_inner_innertileSpatial')
batch_matmul_b_inner_inner_inner_outer = model.NewIntVar(1, 96, 'batch_matmul_b_inner_inner_inner_outer')
batch_matmul_b_inner_inner_inner_inner = model.NewIntVar(1, 96, 'batch_matmul_b_inner_inner_inner_inner')
batch_matmuli_inner_inner_innertileSpatial = model.NewIntVar(1, 2048, 'batch_matmuli_inner_inner_innertileSpatial')
batch_matmul_i_inner_inner_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_i_inner_inner_inner_outer')
batch_matmul_i_inner_inner_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_i_inner_inner_inner_inner')
batch_matmulj_inner_inner_innertileSpatial = model.NewIntVar(1, 2048, 'batch_matmulj_inner_inner_innertileSpatial')
batch_matmul_j_inner_inner_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_j_inner_inner_inner_outer')
batch_matmul_j_inner_inner_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_j_inner_inner_inner_inner')
threadIdx_x = model.NewIntVar(32, 32, 'threadIdx_x')
batch_matmulb_inner_inner_innertileSpatial_batch_matmuli_inner_inner_innertileSpatial = model.NewIntVar(1, 1024, 'batch_matmulb_inner_inner_innertileSpatial_batch_matmuli_inner_inner_innertileSpatial')
batch_matmul_b_inner_inner_inner_outer_i_inner_inner_inner_outer_fused_j_inner_inner_inner_outer_fused = model.NewIntVar(1, 1000000, 'batch_matmul_b_inner_inner_inner_outer_i_inner_inner_inner_outer_fused_j_inner_inner_inner_outer_fused')
batch_matmul_b_inner_inner_inner_outer_batch_matmul_i_inner_inner_inner_outer = model.NewIntVar(1, 1000000, 'batch_matmul_b_inner_inner_inner_outer_batch_matmul_i_inner_inner_inner_outer')
batch_matmul_vectorize = model.NewIntVar(1, 8, 'batch_matmul_vectorize')
batch_matmul_vectorize_cand0 = model.NewIntVar(0, 1, 'batch_matmul_vectorize_cand0')
batch_matmul_vectorize_cand1 = model.NewIntVar(0, 1, 'batch_matmul_vectorize_cand1')
batch_matmul_vectorize_cand2 = model.NewIntVar(0, 1, 'batch_matmul_vectorize_cand2')
batch_matmul_vectorize_cand3 = model.NewIntVar(0, 1, 'batch_matmul_vectorize_cand3')
batch_matmulb_inner_inner_inner_innertileSpatial = model.NewIntVar(1, 96, 'batch_matmulb_inner_inner_inner_innertileSpatial')
batch_matmul_b_inner_inner_inner_inner_outer = model.NewIntVar(1, 96, 'batch_matmul_b_inner_inner_inner_inner_outer')
batch_matmul_b_inner_inner_inner_inner_inner = model.NewIntVar(1, 96, 'batch_matmul_b_inner_inner_inner_inner_inner')
batch_matmuli_inner_inner_inner_innertileSpatial = model.NewIntVar(1, 2048, 'batch_matmuli_inner_inner_inner_innertileSpatial')
batch_matmul_i_inner_inner_inner_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_i_inner_inner_inner_inner_outer')
batch_matmul_i_inner_inner_inner_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_i_inner_inner_inner_inner_inner')
batch_matmulj_inner_inner_inner_innertileSpatial = model.NewIntVar(1, 2048, 'batch_matmulj_inner_inner_inner_innertileSpatial')
batch_matmul_j_inner_inner_inner_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_j_inner_inner_inner_inner_outer')
batch_matmul_j_inner_inner_inner_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_j_inner_inner_inner_inner_inner')
batch_matmul_b_inner_inner_inner_inner_inner_i_inner_inner_inner_inner_inner_fused_j_inner_inner_inner_inner_inner_fused = model.NewIntVar(1, 1000000, 'batch_matmul_b_inner_inner_inner_inner_inner_i_inner_inner_inner_inner_inner_fused_j_inner_inner_inner_inner_inner_fused')
batch_matmul_b_inner_inner_inner_inner_inner_batch_matmul_i_inner_inner_inner_inner_inner = model.NewIntVar(1, 1000000, 'batch_matmul_b_inner_inner_inner_inner_inner_batch_matmul_i_inner_inner_inner_inner_inner')
batch_matmul_wmma_accumulator_shared_ax0 = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_shared_ax0')
batch_matmul_shared_pos_select0 = model.NewIntVar(0, 1, 'batch_matmul_shared_pos_select0')
batch_matmul_shared_pos_select1 = model.NewIntVar(0, 1, 'batch_matmul_shared_pos_select1')
batch_matmul_shared_pos_select2 = model.NewIntVar(0, 1, 'batch_matmul_shared_pos_select2')
batch_matmul_shared_pos_select3 = model.NewIntVar(0, 1, 'batch_matmul_shared_pos_select3')
batch_matmul_shared_pos_select4 = model.NewIntVar(0, 1, 'batch_matmul_shared_pos_select4')
batch_matmul_shared_pos_select5 = model.NewIntVar(0, 1, 'batch_matmul_shared_pos_select5')
batch_matmul_wmma_accumulator_shared_ax1 = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_shared_ax1')
batch_matmul_wmma_accumulator_shared_ax2 = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_shared_ax2')
batch_matmul_wmma_accumulator_shared_offset = model.NewIntVar(0, 48, 'batch_matmul_wmma_accumulator_shared_offset')
batch_matmul_wmma_accumulator_shared_offset_cand0 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_shared_offset_cand0')
batch_matmul_wmma_accumulator_shared_offset_cand1 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_shared_offset_cand1')
batch_matmul_wmma_accumulator_shared_offset_cand2 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_shared_offset_cand2')
batch_matmul_wmma_accumulator_shared_offset_cand3 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_shared_offset_cand3')
batch_matmul_wmma_accumulator_shared_offset_cand4 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_shared_offset_cand4')
batch_matmul_wmma_accumulator_shared_offset_cand5 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_shared_offset_cand5')
batch_matmul_wmma_accumulator_shared_align_size = model.NewIntVar(1, 88888888, 'batch_matmul_wmma_accumulator_shared_align_size')
batch_matmul_wmma_accumulator_sharedax0tileSpatial = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_sharedax0tileSpatial')
batch_matmul_wmma_accumulator_shared_ax0_outer = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_shared_ax0_outer')
batch_matmul_wmma_accumulator_shared_ax0_inner = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_shared_ax0_inner')
batch_matmul_wmma_accumulator_sharedax1tileSpatial = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_sharedax1tileSpatial')
batch_matmul_wmma_accumulator_shared_ax1_outer = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_shared_ax1_outer')
batch_matmul_wmma_accumulator_shared_ax1_inner = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_shared_ax1_inner')
batch_matmul_wmma_accumulator_sharedax2tileSpatial = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_sharedax2tileSpatial')
batch_matmul_wmma_accumulator_shared_ax2_outer = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_shared_ax2_outer')
batch_matmul_wmma_accumulator_shared_ax2_inner = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_shared_ax2_inner')
batch_matmul_wmma_accumulator_sharedax0tileSpatial_batch_matmul_wmma_accumulator_sharedax1tileSpatial = model.NewIntVar(1, 1024, 'batch_matmul_wmma_accumulator_sharedax0tileSpatial_batch_matmul_wmma_accumulator_sharedax1tileSpatial')
batch_matmul_wmma_accumulator_shared_ax0_outer_ax1_outer_fused_ax2_outer_fused = model.NewIntVar(1, 1000000, 'batch_matmul_wmma_accumulator_shared_ax0_outer_ax1_outer_fused_ax2_outer_fused')
batch_matmul_wmma_accumulator_shared_ax0_outer_batch_matmul_wmma_accumulator_shared_ax1_outer = model.NewIntVar(1, 1000000, 'batch_matmul_wmma_accumulator_shared_ax0_outer_batch_matmul_wmma_accumulator_shared_ax1_outer')
batch_matmul_wmma_accumulator_shared_ax0_inner_outer = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_shared_ax0_inner_outer')
batch_matmul_wmma_accumulator_shared_ax0_inner_inner = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_shared_ax0_inner_inner')
batch_matmul_wmma_accumulator_shared_ax1_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_shared_ax1_inner_outer')
batch_matmul_wmma_accumulator_shared_ax1_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_shared_ax1_inner_inner')
batch_matmul_wmma_accumulator_shared_ax2_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_shared_ax2_inner_outer')
batch_matmul_wmma_accumulator_shared_ax2_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_shared_ax2_inner_inner')
batch_matmul_wmma_accumulator_b_c = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_b_c')
batch_matmul_wmma_accumulator_shared_local_pos_select0 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_shared_local_pos_select0')
batch_matmul_wmma_accumulator_shared_local_pos_select1 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_shared_local_pos_select1')
batch_matmul_wmma_accumulator_i_c = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_i_c')
batch_matmul_wmma_accumulator_j_c = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_j_c')
batch_matmul_wmma_accumulatorb_ctileAll = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulatorb_ctileAll')
batch_matmul_wmma_accumulator_b_c_outer = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_b_c_outer')
batch_matmul_wmma_accumulator_b_c_inner = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_b_c_inner')
batch_matmul_wmma_accumulatori_ctileAll = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulatori_ctileAll')
batch_matmul_wmma_accumulator_i_c_outer = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_i_c_outer')
batch_matmul_wmma_accumulator_i_c_inner = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_i_c_inner')
batch_matmul_wmma_accumulatorj_ctileAll = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulatorj_ctileAll')
batch_matmul_wmma_accumulator_j_c_outer = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_j_c_outer')
batch_matmul_wmma_accumulator_j_c_inner = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_j_c_inner')
batch_matmul_wmma_accumulatorktileAll = model.NewIntVar(1, 128, 'batch_matmul_wmma_accumulatorktileAll')
batch_matmul_wmma_accumulator_k_outer = model.NewIntVar(1, 128, 'batch_matmul_wmma_accumulator_k_outer')
batch_matmul_wmma_accumulator_k_inner = model.NewIntVar(1, 128, 'batch_matmul_wmma_accumulator_k_inner')
batch_matmul_wmma_accumulatorb_c_innertileAll = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulatorb_c_innertileAll')
batch_matmul_wmma_accumulator_b_c_inner_outer = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_b_c_inner_outer')
batch_matmul_wmma_accumulator_b_c_inner_inner = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_b_c_inner_inner')
batch_matmul_wmma_accumulatori_c_innertileAll = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulatori_c_innertileAll')
batch_matmul_wmma_accumulator_i_c_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_i_c_inner_outer')
batch_matmul_wmma_accumulator_i_c_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_i_c_inner_inner')
batch_matmul_wmma_accumulatorj_c_innertileAll = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulatorj_c_innertileAll')
batch_matmul_wmma_accumulator_j_c_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_j_c_inner_outer')
batch_matmul_wmma_accumulator_j_c_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_j_c_inner_inner')
batch_matmul_wmma_accumulatork_innertileAll = model.NewIntVar(1, 128, 'batch_matmul_wmma_accumulatork_innertileAll')
batch_matmul_wmma_accumulator_k_inner_outer = model.NewIntVar(1, 128, 'batch_matmul_wmma_accumulator_k_inner_outer')
batch_matmul_wmma_accumulator_k_inner_inner = model.NewIntVar(1, 128, 'batch_matmul_wmma_accumulator_k_inner_inner')
batch_matmul_wmma_accumulatorb_c_inner_innertileAll = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulatorb_c_inner_innertileAll')
batch_matmul_wmma_accumulator_b_c_inner_inner_outer = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_b_c_inner_inner_outer')
batch_matmul_wmma_accumulator_b_c_inner_inner_inner = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_b_c_inner_inner_inner')
batch_matmul_wmma_accumulatori_c_inner_innertileAll = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulatori_c_inner_innertileAll')
batch_matmul_wmma_accumulator_i_c_inner_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_i_c_inner_inner_outer')
batch_matmul_wmma_accumulator_i_c_inner_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_i_c_inner_inner_inner')
batch_matmul_wmma_accumulatorj_c_inner_innertileAll = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulatorj_c_inner_innertileAll')
batch_matmul_wmma_accumulator_j_c_inner_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_j_c_inner_inner_outer')
batch_matmul_wmma_accumulator_j_c_inner_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_j_c_inner_inner_inner')
batch_matmul_wmma_accumulatork_inner_innertileAll = model.NewIntVar(1, 128, 'batch_matmul_wmma_accumulatork_inner_innertileAll')
batch_matmul_wmma_accumulator_k_inner_inner_outer = model.NewIntVar(1, 128, 'batch_matmul_wmma_accumulator_k_inner_inner_outer')
batch_matmul_wmma_accumulator_k_inner_inner_inner = model.NewIntVar(1, 128, 'batch_matmul_wmma_accumulator_k_inner_inner_inner')
batch_matmul_wmma_accumulator_b_c_inner_inner_inner_outer = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_b_c_inner_inner_inner_outer')
batch_matmul_wmma_accumulator_b_c_inner_inner_inner_inner = model.NewIntVar(1, 96, 'batch_matmul_wmma_accumulator_b_c_inner_inner_inner_inner')
batch_matmul_wmma_accumulator_i_c_inner_inner_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_i_c_inner_inner_inner_outer')
batch_matmul_wmma_accumulator_i_c_inner_inner_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_i_c_inner_inner_inner_inner')
batch_matmul_wmma_accumulator_j_c_inner_inner_inner_outer = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_j_c_inner_inner_inner_outer')
batch_matmul_wmma_accumulator_j_c_inner_inner_inner_inner = model.NewIntVar(1, 2048, 'batch_matmul_wmma_accumulator_j_c_inner_inner_inner_inner')
batch_matmul_wmma_accumulator_k_inner_inner_inner_outer = model.NewIntVar(1, 128, 'batch_matmul_wmma_accumulator_k_inner_inner_inner_outer')
batch_matmul_wmma_accumulator_k_inner_inner_inner_inner = model.NewIntVar(1, 128, 'batch_matmul_wmma_accumulator_k_inner_inner_inner_inner')
B_shared_wmma_matrix_b_ax0 = model.NewIntVar(1, 96, 'B_shared_wmma_matrix_b_ax0')
batch_matmul_wmma_accumulator_local_pos_select0 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_local_pos_select0')
batch_matmul_wmma_accumulator_local_pos_select1 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_local_pos_select1')
batch_matmul_wmma_accumulator_local_pos_select2 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_local_pos_select2')
batch_matmul_wmma_accumulator_local_pos_select3 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_local_pos_select3')
B_shared_wmma_matrix_b_ax1 = model.NewIntVar(1, 2048, 'B_shared_wmma_matrix_b_ax1')
B_shared_wmma_matrix_b_ax2 = model.NewIntVar(1, 128, 'B_shared_wmma_matrix_b_ax2')
B_shared_wmma_matrix_b_ax0_outer = model.NewIntVar(1, 96, 'B_shared_wmma_matrix_b_ax0_outer')
B_shared_wmma_matrix_b_ax0_inner = model.NewIntVar(1, 96, 'B_shared_wmma_matrix_b_ax0_inner')
B_shared_wmma_matrix_b_ax1_outer = model.NewIntVar(1, 2048, 'B_shared_wmma_matrix_b_ax1_outer')
B_shared_wmma_matrix_b_ax1_inner = model.NewIntVar(1, 2048, 'B_shared_wmma_matrix_b_ax1_inner')
B_shared_wmma_matrix_b_ax2_outer = model.NewIntVar(1, 128, 'B_shared_wmma_matrix_b_ax2_outer')
B_shared_wmma_matrix_b_ax2_inner = model.NewIntVar(1, 128, 'B_shared_wmma_matrix_b_ax2_inner')
B_shared_ax0 = model.NewIntVar(1, 96, 'B_shared_ax0')
B_shared_tmp_ax0 = model.NewIntVar(1, 96, 'B_shared_tmp_ax0')
batch_matmul_wmma_accumulator_shared_pos_select0 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_shared_pos_select0')
batch_matmul_wmma_accumulator_shared_pos_select1 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_shared_pos_select1')
batch_matmul_wmma_accumulator_shared_pos_select2 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_shared_pos_select2')
batch_matmul_wmma_accumulator_shared_pos_select3 = model.NewIntVar(0, 1, 'batch_matmul_wmma_accumulator_shared_pos_select3')
B_shared_ax1 = model.NewIntVar(1, 2048, 'B_shared_ax1')
B_shared_tmp_ax1 = model.NewIntVar(1, 2048, 'B_shared_tmp_ax1')
B_shared_ax2 = model.NewIntVar(1, 128, 'B_shared_ax2')
B_shared_offset = model.NewIntVar(0, 48, 'B_shared_offset')
B_shared_offset_cand0 = model.NewIntVar(0, 1, 'B_shared_offset_cand0')
B_shared_offset_cand1 = model.NewIntVar(0, 1, 'B_shared_offset_cand1')
B_shared_offset_cand2 = model.NewIntVar(0, 1, 'B_shared_offset_cand2')
B_shared_offset_cand3 = model.NewIntVar(0, 1, 'B_shared_offset_cand3')
B_shared_offset_cand4 = model.NewIntVar(0, 1, 'B_shared_offset_cand4')
B_shared_offset_cand5 = model.NewIntVar(0, 1, 'B_shared_offset_cand5')
B_shared_align_size = model.NewIntVar(1, 88888888, 'B_shared_align_size')
B_shared_ax0_ax1_fused_ax2_fused = model.NewIntVar(1, 1000000, 'B_shared_ax0_ax1_fused_ax2_fused')
B_shared_ax0_B_shared_ax1 = model.NewIntVar(1, 1000000, 'B_shared_ax0_B_shared_ax1')
B_shared_vectorize = model.NewIntVar(1, 8, 'B_shared_vectorize')
B_shared_vectorize_cand0 = model.NewIntVar(0, 1, 'B_shared_vectorize_cand0')
B_shared_vectorize_cand1 = model.NewIntVar(0, 1, 'B_shared_vectorize_cand1')
B_shared_vectorize_cand2 = model.NewIntVar(0, 1, 'B_shared_vectorize_cand2')
B_shared_vectorize_cand3 = model.NewIntVar(0, 1, 'B_shared_vectorize_cand3')
A_shared_wmma_matrix_a_ax0 = model.NewIntVar(1, 96, 'A_shared_wmma_matrix_a_ax0')
A_shared_wmma_matrix_a_ax1 = model.NewIntVar(1, 2048, 'A_shared_wmma_matrix_a_ax1')
A_shared_wmma_matrix_a_ax2 = model.NewIntVar(1, 128, 'A_shared_wmma_matrix_a_ax2')
A_shared_wmma_matrix_a_ax0_outer = model.NewIntVar(1, 96, 'A_shared_wmma_matrix_a_ax0_outer')
A_shared_wmma_matrix_a_ax0_inner = model.NewIntVar(1, 96, 'A_shared_wmma_matrix_a_ax0_inner')
A_shared_wmma_matrix_a_ax1_outer = model.NewIntVar(1, 2048, 'A_shared_wmma_matrix_a_ax1_outer')
A_shared_wmma_matrix_a_ax1_inner = model.NewIntVar(1, 2048, 'A_shared_wmma_matrix_a_ax1_inner')
A_shared_wmma_matrix_a_ax2_outer = model.NewIntVar(1, 128, 'A_shared_wmma_matrix_a_ax2_outer')
A_shared_wmma_matrix_a_ax2_inner = model.NewIntVar(1, 128, 'A_shared_wmma_matrix_a_ax2_inner')
A_shared_ax0 = model.NewIntVar(1, 96, 'A_shared_ax0')
A_shared_tmp_ax0 = model.NewIntVar(1, 96, 'A_shared_tmp_ax0')
A_shared_ax1 = model.NewIntVar(1, 2048, 'A_shared_ax1')
A_shared_tmp_ax1 = model.NewIntVar(1, 2048, 'A_shared_tmp_ax1')
A_shared_ax2 = model.NewIntVar(1, 128, 'A_shared_ax2')
A_shared_offset = model.NewIntVar(0, 48, 'A_shared_offset')
A_shared_offset_cand0 = model.NewIntVar(0, 1, 'A_shared_offset_cand0')
A_shared_offset_cand1 = model.NewIntVar(0, 1, 'A_shared_offset_cand1')
A_shared_offset_cand2 = model.NewIntVar(0, 1, 'A_shared_offset_cand2')
A_shared_offset_cand3 = model.NewIntVar(0, 1, 'A_shared_offset_cand3')
A_shared_offset_cand4 = model.NewIntVar(0, 1, 'A_shared_offset_cand4')
A_shared_offset_cand5 = model.NewIntVar(0, 1, 'A_shared_offset_cand5')
A_shared_align_size = model.NewIntVar(1, 88888888, 'A_shared_align_size')
A_shared_ax0_ax1_fused_ax2_fused = model.NewIntVar(1, 1000000, 'A_shared_ax0_ax1_fused_ax2_fused')
A_shared_ax0_A_shared_ax1 = model.NewIntVar(1, 1000000, 'A_shared_ax0_A_shared_ax1')
A_shared_vectorize = model.NewIntVar(1, 8, 'A_shared_vectorize')
A_shared_vectorize_cand0 = model.NewIntVar(0, 1, 'A_shared_vectorize_cand0')
A_shared_vectorize_cand1 = model.NewIntVar(0, 1, 'A_shared_vectorize_cand1')
A_shared_vectorize_cand2 = model.NewIntVar(0, 1, 'A_shared_vectorize_cand2')
A_shared_vectorize_cand3 = model.NewIntVar(0, 1, 'A_shared_vectorize_cand3')
threads = model.NewIntVar(1, 1024, 'threads')
A_shared_shared_mem_size = model.NewIntVar(1, 24576, 'A_shared_shared_mem_size')
B_shared_shared_mem_size = model.NewIntVar(1, 24576, 'B_shared_shared_mem_size')
batch_matmul_wmma_accumulator_shared_shared_mem_size = model.NewIntVar(1, 24576, 'batch_matmul_wmma_accumulator_shared_shared_mem_size')
batch_matmul_wmma_accumulator_shared_ax0_batch_matmul_wmma_accumulator_shared_ax1 = model.NewIntVar(1, 24576, 'batch_matmul_wmma_accumulator_shared_ax0_batch_matmul_wmma_accumulator_shared_ax1')
model.Add(wmma_m == 8).OnlyEnforceIf(wmma_m_cand0)
model.Add(wmma_m == 16).OnlyEnforceIf(wmma_m_cand1)
model.Add(wmma_m == 32).OnlyEnforceIf(wmma_m_cand2)
model.Add(sum([wmma_m_cand0, wmma_m_cand1, wmma_m_cand2]) == 1)
model.Add(wmma_n == 8).OnlyEnforceIf(wmma_n_cand0)
model.Add(wmma_n == 16).OnlyEnforceIf(wmma_n_cand1)
model.Add(wmma_n == 32).OnlyEnforceIf(wmma_n_cand2)
model.Add(sum([wmma_n_cand0, wmma_n_cand1, wmma_n_cand2]) == 1)
model.AddMultiplicationEquality(wmma_m_wmma_n, [wmma_m, wmma_n])
model.AddMultiplicationEquality(4096, [wmma_m_wmma_n, wmma_k])
model.AddMultiplicationEquality(96, [batch_matmul_b_outer, batch_matmul_b_inner])
model.Add(batch_matmul_b_outer == 1)
model.AddMultiplicationEquality(2048, [batch_matmul_i_outer, batch_matmul_i_inner])
model.Add(batch_matmul_i_outer == 1)
model.AddMultiplicationEquality(2048, [batch_matmul_j_outer, batch_matmul_j_inner])
model.Add(batch_matmul_j_outer == 1)
model.AddMultiplicationEquality(batch_matmul_b_inner, [batch_matmul_b_inner_outer, batch_matmul_b_inner_inner])
model.Add(batch_matmul_b_inner_outer == batch_matmulb_innertileSpatial)
model.AddMultiplicationEquality(batch_matmul_i_inner, [batch_matmul_i_inner_outer, batch_matmul_i_inner_inner])
model.Add(batch_matmul_i_inner_outer == batch_matmuli_innertileSpatial)
model.AddMultiplicationEquality(batch_matmul_j_inner, [batch_matmul_j_inner_outer, batch_matmul_j_inner_inner])
model.Add(batch_matmul_j_inner_outer == batch_matmulj_innertileSpatial)
model.AddMultiplicationEquality(batch_matmulb_innertileSpatial_batch_matmuli_innertileSpatial, [batch_matmulb_innertileSpatial, batch_matmuli_innertileSpatial])
model.AddMultiplicationEquality(blockIdx_x, [batch_matmulb_innertileSpatial_batch_matmuli_innertileSpatial, batch_matmulj_innertileSpatial])
model.AddMultiplicationEquality(batch_matmul_b_inner_outer_batch_matmul_i_inner_outer, [batch_matmul_b_inner_outer, batch_matmul_i_inner_outer])
model.AddMultiplicationEquality(batch_matmul_b_inner_outer_i_inner_outer_fused_j_inner_outer_fused, [batch_matmul_b_inner_outer_batch_matmul_i_inner_outer, batch_matmul_j_inner_outer])
model.AddMultiplicationEquality(batch_matmul_b_inner_inner, [batch_matmul_b_inner_inner_outer, batch_matmul_b_inner_inner_inner])
model.Add(batch_matmul_b_inner_inner_outer == batch_matmulb_inner_innertileSpatial)
model.AddMultiplicationEquality(batch_matmul_i_inner_inner, [batch_matmul_i_inner_inner_outer, batch_matmul_i_inner_inner_inner])
model.Add(batch_matmul_i_inner_inner_outer == batch_matmuli_inner_innertileSpatial)
model.AddMultiplicationEquality(batch_matmul_j_inner_inner, [batch_matmul_j_inner_inner_outer, batch_matmul_j_inner_inner_inner])
model.Add(batch_matmul_j_inner_inner_outer == batch_matmulj_inner_innertileSpatial)
model.AddMultiplicationEquality(batch_matmulb_inner_innertileSpatial_batch_matmuli_inner_innertileSpatial, [batch_matmulb_inner_innertileSpatial, batch_matmuli_inner_innertileSpatial])
model.AddMultiplicationEquality(threadIdx_y, [batch_matmulb_inner_innertileSpatial_batch_matmuli_inner_innertileSpatial, batch_matmulj_inner_innertileSpatial])
model.AddMultiplicationEquality(batch_matmul_b_inner_inner_outer_batch_matmul_i_inner_inner_outer, [batch_matmul_b_inner_inner_outer, batch_matmul_i_inner_inner_outer])
model.AddMultiplicationEquality(batch_matmul_b_inner_inner_outer_i_inner_inner_outer_fused_j_inner_inner_outer_fused, [batch_matmul_b_inner_inner_outer_batch_matmul_i_inner_inner_outer, batch_matmul_j_inner_inner_outer])
model.AddMultiplicationEquality(batch_matmul_b_inner_inner_inner, [batch_matmul_b_inner_inner_inner_outer, batch_matmul_b_inner_inner_inner_inner])
model.Add(batch_matmul_b_inner_inner_inner_outer == batch_matmulb_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(batch_matmul_i_inner_inner_inner, [batch_matmul_i_inner_inner_inner_outer, batch_matmul_i_inner_inner_inner_inner])
model.Add(batch_matmul_i_inner_inner_inner_outer == batch_matmuli_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(batch_matmul_j_inner_inner_inner, [batch_matmul_j_inner_inner_inner_outer, batch_matmul_j_inner_inner_inner_inner])
model.Add(batch_matmul_j_inner_inner_inner_outer == batch_matmulj_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(batch_matmulb_inner_inner_innertileSpatial_batch_matmuli_inner_inner_innertileSpatial, [batch_matmulb_inner_inner_innertileSpatial, batch_matmuli_inner_inner_innertileSpatial])
model.AddMultiplicationEquality(threadIdx_x, [batch_matmulb_inner_inner_innertileSpatial_batch_matmuli_inner_inner_innertileSpatial, batch_matmulj_inner_inner_innertileSpatial])
model.AddMultiplicationEquality(batch_matmul_b_inner_inner_inner_outer_batch_matmul_i_inner_inner_inner_outer, [batch_matmul_b_inner_inner_inner_outer, batch_matmul_i_inner_inner_inner_outer])
model.AddMultiplicationEquality(batch_matmul_b_inner_inner_inner_outer_i_inner_inner_inner_outer_fused_j_inner_inner_inner_outer_fused, [batch_matmul_b_inner_inner_inner_outer_batch_matmul_i_inner_inner_inner_outer, batch_matmul_j_inner_inner_inner_outer])
model.Add(batch_matmul_vectorize == 1).OnlyEnforceIf(batch_matmul_vectorize_cand0)
model.Add(batch_matmul_vectorize == 2).OnlyEnforceIf(batch_matmul_vectorize_cand1)
model.Add(batch_matmul_vectorize == 4).OnlyEnforceIf(batch_matmul_vectorize_cand2)
model.Add(batch_matmul_vectorize == 8).OnlyEnforceIf(batch_matmul_vectorize_cand3)
model.Add(sum([batch_matmul_vectorize_cand0, batch_matmul_vectorize_cand1, batch_matmul_vectorize_cand2, batch_matmul_vectorize_cand3]) == 1)
model.AddMultiplicationEquality(batch_matmul_b_inner_inner_inner_inner, [batch_matmul_b_inner_inner_inner_inner_outer, batch_matmul_b_inner_inner_inner_inner_inner])
model.Add(batch_matmul_b_inner_inner_inner_inner_outer == batch_matmulb_inner_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(batch_matmul_i_inner_inner_inner_inner, [batch_matmul_i_inner_inner_inner_inner_outer, batch_matmul_i_inner_inner_inner_inner_inner])
model.Add(batch_matmul_i_inner_inner_inner_inner_outer == batch_matmuli_inner_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(batch_matmul_j_inner_inner_inner_inner, [batch_matmul_j_inner_inner_inner_inner_outer, batch_matmul_j_inner_inner_inner_inner_inner])
model.Add(batch_matmul_j_inner_inner_inner_inner_outer == batch_matmulj_inner_inner_inner_innertileSpatial)
model.AddMultiplicationEquality(batch_matmul_b_inner_inner_inner_inner_inner_batch_matmul_i_inner_inner_inner_inner_inner, [batch_matmul_b_inner_inner_inner_inner_inner, batch_matmul_i_inner_inner_inner_inner_inner])
model.AddMultiplicationEquality(batch_matmul_b_inner_inner_inner_inner_inner_i_inner_inner_inner_inner_inner_fused_j_inner_inner_inner_inner_inner_fused, [batch_matmul_b_inner_inner_inner_inner_inner_batch_matmul_i_inner_inner_inner_inner_inner, batch_matmul_j_inner_inner_inner_inner_inner])
model.Add(batch_matmul_b_inner_inner_inner_inner_inner_i_inner_inner_inner_inner_inner_fused_j_inner_inner_inner_inner_inner_fused == batch_matmul_vectorize)
model.Add(batch_matmul_shared_pos != 0)
model.Add(batch_matmul_wmma_accumulator_shared_ax0 == batch_matmul_b_inner).OnlyEnforceIf(batch_matmul_shared_pos_select0)
model.Add(batch_matmul_shared_pos == 0).OnlyEnforceIf(batch_matmul_shared_pos_select0)
model.Add(batch_matmul_wmma_accumulator_shared_ax0 == batch_matmul_b_inner_inner).OnlyEnforceIf(batch_matmul_shared_pos_select1)
model.Add(batch_matmul_shared_pos == 1).OnlyEnforceIf(batch_matmul_shared_pos_select1)
model.Add(batch_matmul_wmma_accumulator_shared_ax0 == batch_matmul_b_inner_inner_inner).OnlyEnforceIf(batch_matmul_shared_pos_select2)
model.Add(batch_matmul_shared_pos == 2).OnlyEnforceIf(batch_matmul_shared_pos_select2)
model.Add(batch_matmul_wmma_accumulator_shared_ax0 == batch_matmul_b_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_shared_pos_select3)
model.Add(batch_matmul_shared_pos == 3).OnlyEnforceIf(batch_matmul_shared_pos_select3)
model.Add(batch_matmul_wmma_accumulator_shared_ax0 == batch_matmul_b_inner_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_shared_pos_select4)
model.Add(batch_matmul_shared_pos == 4).OnlyEnforceIf(batch_matmul_shared_pos_select4)
model.Add(batch_matmul_wmma_accumulator_shared_ax0 == 1).OnlyEnforceIf(batch_matmul_shared_pos_select5)
model.Add(batch_matmul_shared_pos == 5).OnlyEnforceIf(batch_matmul_shared_pos_select5)
model.Add(sum([batch_matmul_shared_pos_select0, batch_matmul_shared_pos_select1, batch_matmul_shared_pos_select2, batch_matmul_shared_pos_select3, batch_matmul_shared_pos_select4, batch_matmul_shared_pos_select5]) == 1)
model.Add(batch_matmul_wmma_accumulator_shared_ax1 == batch_matmul_i_inner).OnlyEnforceIf(batch_matmul_shared_pos_select0)
model.Add(batch_matmul_shared_pos == 0).OnlyEnforceIf(batch_matmul_shared_pos_select0)
model.Add(batch_matmul_wmma_accumulator_shared_ax1 == batch_matmul_i_inner_inner).OnlyEnforceIf(batch_matmul_shared_pos_select1)
model.Add(batch_matmul_shared_pos == 1).OnlyEnforceIf(batch_matmul_shared_pos_select1)
model.Add(batch_matmul_wmma_accumulator_shared_ax1 == batch_matmul_i_inner_inner_inner).OnlyEnforceIf(batch_matmul_shared_pos_select2)
model.Add(batch_matmul_shared_pos == 2).OnlyEnforceIf(batch_matmul_shared_pos_select2)
model.Add(batch_matmul_wmma_accumulator_shared_ax1 == batch_matmul_i_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_shared_pos_select3)
model.Add(batch_matmul_shared_pos == 3).OnlyEnforceIf(batch_matmul_shared_pos_select3)
model.Add(batch_matmul_wmma_accumulator_shared_ax1 == batch_matmul_i_inner_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_shared_pos_select4)
model.Add(batch_matmul_shared_pos == 4).OnlyEnforceIf(batch_matmul_shared_pos_select4)
model.Add(batch_matmul_wmma_accumulator_shared_ax1 == 1).OnlyEnforceIf(batch_matmul_shared_pos_select5)
model.Add(batch_matmul_shared_pos == 5).OnlyEnforceIf(batch_matmul_shared_pos_select5)
model.Add(sum([batch_matmul_shared_pos_select0, batch_matmul_shared_pos_select1, batch_matmul_shared_pos_select2, batch_matmul_shared_pos_select3, batch_matmul_shared_pos_select4, batch_matmul_shared_pos_select5]) == 1)
model.Add(batch_matmul_wmma_accumulator_shared_ax2 == batch_matmul_j_inner).OnlyEnforceIf(batch_matmul_shared_pos_select0)
model.Add(batch_matmul_shared_pos == 0).OnlyEnforceIf(batch_matmul_shared_pos_select0)
model.Add(batch_matmul_wmma_accumulator_shared_ax2 == batch_matmul_j_inner_inner).OnlyEnforceIf(batch_matmul_shared_pos_select1)
model.Add(batch_matmul_shared_pos == 1).OnlyEnforceIf(batch_matmul_shared_pos_select1)
model.Add(batch_matmul_wmma_accumulator_shared_ax2 == batch_matmul_j_inner_inner_inner).OnlyEnforceIf(batch_matmul_shared_pos_select2)
model.Add(batch_matmul_shared_pos == 2).OnlyEnforceIf(batch_matmul_shared_pos_select2)
model.Add(batch_matmul_wmma_accumulator_shared_ax2 == batch_matmul_j_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_shared_pos_select3)
model.Add(batch_matmul_shared_pos == 3).OnlyEnforceIf(batch_matmul_shared_pos_select3)
model.Add(batch_matmul_wmma_accumulator_shared_ax2 == batch_matmul_j_inner_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_shared_pos_select4)
model.Add(batch_matmul_shared_pos == 4).OnlyEnforceIf(batch_matmul_shared_pos_select4)
model.Add(batch_matmul_wmma_accumulator_shared_ax2 == 1).OnlyEnforceIf(batch_matmul_shared_pos_select5)
model.Add(batch_matmul_shared_pos == 5).OnlyEnforceIf(batch_matmul_shared_pos_select5)
model.Add(sum([batch_matmul_shared_pos_select0, batch_matmul_shared_pos_select1, batch_matmul_shared_pos_select2, batch_matmul_shared_pos_select3, batch_matmul_shared_pos_select4, batch_matmul_shared_pos_select5]) == 1)
model.Add(batch_matmul_wmma_accumulator_shared_offset == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_offset_cand0)
model.Add(batch_matmul_wmma_accumulator_shared_offset == 8).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_offset_cand1)
model.Add(batch_matmul_wmma_accumulator_shared_offset == 16).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_offset_cand2)
model.Add(batch_matmul_wmma_accumulator_shared_offset == 24).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_offset_cand3)
model.Add(batch_matmul_wmma_accumulator_shared_offset == 32).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_offset_cand4)
model.Add(batch_matmul_wmma_accumulator_shared_offset == 48).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_offset_cand5)
model.Add(sum([batch_matmul_wmma_accumulator_shared_offset_cand0, batch_matmul_wmma_accumulator_shared_offset_cand1, batch_matmul_wmma_accumulator_shared_offset_cand2, batch_matmul_wmma_accumulator_shared_offset_cand3, batch_matmul_wmma_accumulator_shared_offset_cand4, batch_matmul_wmma_accumulator_shared_offset_cand5]) == 1)
model.Add(sum([batch_matmul_wmma_accumulator_shared_ax2, batch_matmul_wmma_accumulator_shared_offset]) == batch_matmul_wmma_accumulator_shared_align_size)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_shared_ax0, [batch_matmul_wmma_accumulator_shared_ax0_outer, batch_matmul_wmma_accumulator_shared_ax0_inner])
model.Add(batch_matmul_wmma_accumulator_shared_ax0_outer == batch_matmul_wmma_accumulator_sharedax0tileSpatial)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_shared_ax1, [batch_matmul_wmma_accumulator_shared_ax1_outer, batch_matmul_wmma_accumulator_shared_ax1_inner])
model.Add(batch_matmul_wmma_accumulator_shared_ax1_outer == batch_matmul_wmma_accumulator_sharedax1tileSpatial)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_shared_ax2, [batch_matmul_wmma_accumulator_shared_ax2_outer, batch_matmul_wmma_accumulator_shared_ax2_inner])
model.Add(batch_matmul_wmma_accumulator_shared_ax2_outer == batch_matmul_wmma_accumulator_sharedax2tileSpatial)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_sharedax0tileSpatial_batch_matmul_wmma_accumulator_sharedax1tileSpatial, [batch_matmul_wmma_accumulator_sharedax0tileSpatial, batch_matmul_wmma_accumulator_sharedax1tileSpatial])
model.AddMultiplicationEquality(threadIdx_y, [batch_matmul_wmma_accumulator_sharedax0tileSpatial_batch_matmul_wmma_accumulator_sharedax1tileSpatial, batch_matmul_wmma_accumulator_sharedax2tileSpatial])
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_shared_ax0_outer_batch_matmul_wmma_accumulator_shared_ax1_outer, [batch_matmul_wmma_accumulator_shared_ax0_outer, batch_matmul_wmma_accumulator_shared_ax1_outer])
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_shared_ax0_outer_ax1_outer_fused_ax2_outer_fused, [batch_matmul_wmma_accumulator_shared_ax0_outer_batch_matmul_wmma_accumulator_shared_ax1_outer, batch_matmul_wmma_accumulator_shared_ax2_outer])
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_shared_ax0_inner, [batch_matmul_wmma_accumulator_shared_ax0_inner_outer, batch_matmul_wmma_accumulator_shared_ax0_inner_inner])
model.Add(batch_matmul_wmma_accumulator_shared_ax0_inner_inner == 1)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_shared_ax1_inner, [batch_matmul_wmma_accumulator_shared_ax1_inner_outer, batch_matmul_wmma_accumulator_shared_ax1_inner_inner])
model.Add(batch_matmul_wmma_accumulator_shared_ax1_inner_inner == wmma_m)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_shared_ax2_inner, [batch_matmul_wmma_accumulator_shared_ax2_inner_outer, batch_matmul_wmma_accumulator_shared_ax2_inner_inner])
model.Add(batch_matmul_wmma_accumulator_shared_ax2_inner_inner == wmma_n)
model.Add(batch_matmul_wmma_accumulator_b_c == batch_matmul_wmma_accumulator_shared_ax0_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_local_pos_select0)
model.Add(batch_matmul_wmma_accumulator_shared_local_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_local_pos_select0)
model.Add(batch_matmul_wmma_accumulator_b_c == batch_matmul_wmma_accumulator_shared_ax0_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_local_pos_select1)
model.Add(batch_matmul_wmma_accumulator_shared_local_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_local_pos_select1)
model.Add(sum([batch_matmul_wmma_accumulator_shared_local_pos_select0, batch_matmul_wmma_accumulator_shared_local_pos_select1]) == 1)
model.Add(batch_matmul_wmma_accumulator_i_c == batch_matmul_wmma_accumulator_shared_ax1_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_local_pos_select0)
model.Add(batch_matmul_wmma_accumulator_shared_local_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_local_pos_select0)
model.Add(batch_matmul_wmma_accumulator_i_c == batch_matmul_wmma_accumulator_shared_ax1_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_local_pos_select1)
model.Add(batch_matmul_wmma_accumulator_shared_local_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_local_pos_select1)
model.Add(sum([batch_matmul_wmma_accumulator_shared_local_pos_select0, batch_matmul_wmma_accumulator_shared_local_pos_select1]) == 1)
model.Add(batch_matmul_wmma_accumulator_j_c == batch_matmul_wmma_accumulator_shared_ax2_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_local_pos_select0)
model.Add(batch_matmul_wmma_accumulator_shared_local_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_local_pos_select0)
model.Add(batch_matmul_wmma_accumulator_j_c == batch_matmul_wmma_accumulator_shared_ax2_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_local_pos_select1)
model.Add(batch_matmul_wmma_accumulator_shared_local_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_local_pos_select1)
model.Add(sum([batch_matmul_wmma_accumulator_shared_local_pos_select0, batch_matmul_wmma_accumulator_shared_local_pos_select1]) == 1)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_b_c, [batch_matmul_wmma_accumulator_b_c_outer, batch_matmul_wmma_accumulator_b_c_inner])
model.Add(batch_matmul_wmma_accumulator_b_c_outer == batch_matmul_wmma_accumulatorb_ctileAll)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_i_c, [batch_matmul_wmma_accumulator_i_c_outer, batch_matmul_wmma_accumulator_i_c_inner])
model.Add(batch_matmul_wmma_accumulator_i_c_outer == batch_matmul_wmma_accumulatori_ctileAll)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_j_c, [batch_matmul_wmma_accumulator_j_c_outer, batch_matmul_wmma_accumulator_j_c_inner])
model.Add(batch_matmul_wmma_accumulator_j_c_outer == batch_matmul_wmma_accumulatorj_ctileAll)
model.AddMultiplicationEquality(128, [batch_matmul_wmma_accumulator_k_outer, batch_matmul_wmma_accumulator_k_inner])
model.Add(batch_matmul_wmma_accumulator_k_outer == batch_matmul_wmma_accumulatorktileAll)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_b_c_inner, [batch_matmul_wmma_accumulator_b_c_inner_outer, batch_matmul_wmma_accumulator_b_c_inner_inner])
model.Add(batch_matmul_wmma_accumulator_b_c_inner_outer == batch_matmul_wmma_accumulatorb_c_innertileAll)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_i_c_inner, [batch_matmul_wmma_accumulator_i_c_inner_outer, batch_matmul_wmma_accumulator_i_c_inner_inner])
model.Add(batch_matmul_wmma_accumulator_i_c_inner_outer == batch_matmul_wmma_accumulatori_c_innertileAll)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_j_c_inner, [batch_matmul_wmma_accumulator_j_c_inner_outer, batch_matmul_wmma_accumulator_j_c_inner_inner])
model.Add(batch_matmul_wmma_accumulator_j_c_inner_outer == batch_matmul_wmma_accumulatorj_c_innertileAll)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_k_inner, [batch_matmul_wmma_accumulator_k_inner_outer, batch_matmul_wmma_accumulator_k_inner_inner])
model.Add(batch_matmul_wmma_accumulator_k_inner_outer == batch_matmul_wmma_accumulatork_innertileAll)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_b_c_inner_inner, [batch_matmul_wmma_accumulator_b_c_inner_inner_outer, batch_matmul_wmma_accumulator_b_c_inner_inner_inner])
model.Add(batch_matmul_wmma_accumulator_b_c_inner_inner_outer == batch_matmul_wmma_accumulatorb_c_inner_innertileAll)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_i_c_inner_inner, [batch_matmul_wmma_accumulator_i_c_inner_inner_outer, batch_matmul_wmma_accumulator_i_c_inner_inner_inner])
model.Add(batch_matmul_wmma_accumulator_i_c_inner_inner_outer == batch_matmul_wmma_accumulatori_c_inner_innertileAll)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_j_c_inner_inner, [batch_matmul_wmma_accumulator_j_c_inner_inner_outer, batch_matmul_wmma_accumulator_j_c_inner_inner_inner])
model.Add(batch_matmul_wmma_accumulator_j_c_inner_inner_outer == batch_matmul_wmma_accumulatorj_c_inner_innertileAll)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_k_inner_inner, [batch_matmul_wmma_accumulator_k_inner_inner_outer, batch_matmul_wmma_accumulator_k_inner_inner_inner])
model.Add(batch_matmul_wmma_accumulator_k_inner_inner_outer == batch_matmul_wmma_accumulatork_inner_innertileAll)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_b_c_inner_inner_inner, [batch_matmul_wmma_accumulator_b_c_inner_inner_inner_outer, batch_matmul_wmma_accumulator_b_c_inner_inner_inner_inner])
model.Add(batch_matmul_wmma_accumulator_b_c_inner_inner_inner_inner == 1)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_i_c_inner_inner_inner, [batch_matmul_wmma_accumulator_i_c_inner_inner_inner_outer, batch_matmul_wmma_accumulator_i_c_inner_inner_inner_inner])
model.Add(batch_matmul_wmma_accumulator_i_c_inner_inner_inner_inner == wmma_m)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_j_c_inner_inner_inner, [batch_matmul_wmma_accumulator_j_c_inner_inner_inner_outer, batch_matmul_wmma_accumulator_j_c_inner_inner_inner_inner])
model.Add(batch_matmul_wmma_accumulator_j_c_inner_inner_inner_inner == wmma_n)
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_k_inner_inner_inner, [batch_matmul_wmma_accumulator_k_inner_inner_inner_outer, batch_matmul_wmma_accumulator_k_inner_inner_inner_inner])
model.Add(batch_matmul_wmma_accumulator_k_inner_inner_inner_inner == wmma_k)
model.Add(batch_matmul_wmma_accumulator_shared_pos <= batch_matmul_wmma_accumulator_local_pos)
model.Add(B_shared_wmma_matrix_b_ax0 == batch_matmul_wmma_accumulator_b_c_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select0)
model.Add(batch_matmul_wmma_accumulator_local_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select0)
model.Add(B_shared_wmma_matrix_b_ax0 == batch_matmul_wmma_accumulator_b_c_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select1)
model.Add(batch_matmul_wmma_accumulator_local_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select1)
model.Add(B_shared_wmma_matrix_b_ax0 == batch_matmul_wmma_accumulator_b_c_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select2)
model.Add(batch_matmul_wmma_accumulator_local_pos == 2).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select2)
model.Add(B_shared_wmma_matrix_b_ax0 == batch_matmul_wmma_accumulator_b_c_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select3)
model.Add(batch_matmul_wmma_accumulator_local_pos == 3).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select3)
model.Add(sum([batch_matmul_wmma_accumulator_local_pos_select0, batch_matmul_wmma_accumulator_local_pos_select1, batch_matmul_wmma_accumulator_local_pos_select2, batch_matmul_wmma_accumulator_local_pos_select3]) == 1)
model.Add(B_shared_wmma_matrix_b_ax1 == batch_matmul_wmma_accumulator_j_c_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select0)
model.Add(batch_matmul_wmma_accumulator_local_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select0)
model.Add(B_shared_wmma_matrix_b_ax1 == batch_matmul_wmma_accumulator_j_c_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select1)
model.Add(batch_matmul_wmma_accumulator_local_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select1)
model.Add(B_shared_wmma_matrix_b_ax1 == batch_matmul_wmma_accumulator_j_c_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select2)
model.Add(batch_matmul_wmma_accumulator_local_pos == 2).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select2)
model.Add(B_shared_wmma_matrix_b_ax1 == batch_matmul_wmma_accumulator_j_c_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select3)
model.Add(batch_matmul_wmma_accumulator_local_pos == 3).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select3)
model.Add(sum([batch_matmul_wmma_accumulator_local_pos_select0, batch_matmul_wmma_accumulator_local_pos_select1, batch_matmul_wmma_accumulator_local_pos_select2, batch_matmul_wmma_accumulator_local_pos_select3]) == 1)
model.Add(B_shared_wmma_matrix_b_ax2 == batch_matmul_wmma_accumulator_k_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select0)
model.Add(batch_matmul_wmma_accumulator_local_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select0)
model.Add(B_shared_wmma_matrix_b_ax2 == batch_matmul_wmma_accumulator_k_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select1)
model.Add(batch_matmul_wmma_accumulator_local_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select1)
model.Add(B_shared_wmma_matrix_b_ax2 == batch_matmul_wmma_accumulator_k_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select2)
model.Add(batch_matmul_wmma_accumulator_local_pos == 2).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select2)
model.Add(B_shared_wmma_matrix_b_ax2 == batch_matmul_wmma_accumulator_k_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select3)
model.Add(batch_matmul_wmma_accumulator_local_pos == 3).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select3)
model.Add(sum([batch_matmul_wmma_accumulator_local_pos_select0, batch_matmul_wmma_accumulator_local_pos_select1, batch_matmul_wmma_accumulator_local_pos_select2, batch_matmul_wmma_accumulator_local_pos_select3]) == 1)
model.AddMultiplicationEquality(B_shared_wmma_matrix_b_ax0, [B_shared_wmma_matrix_b_ax0_outer, B_shared_wmma_matrix_b_ax0_inner])
model.Add(B_shared_wmma_matrix_b_ax0_inner == 1)
model.AddMultiplicationEquality(B_shared_wmma_matrix_b_ax1, [B_shared_wmma_matrix_b_ax1_outer, B_shared_wmma_matrix_b_ax1_inner])
model.Add(B_shared_wmma_matrix_b_ax1_inner == wmma_n)
model.AddMultiplicationEquality(B_shared_wmma_matrix_b_ax2, [B_shared_wmma_matrix_b_ax2_outer, B_shared_wmma_matrix_b_ax2_inner])
model.Add(B_shared_wmma_matrix_b_ax2_inner == wmma_k)
model.Add(B_shared_tmp_ax0 == batch_matmul_wmma_accumulator_b_c_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select0)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select0)
model.Add(B_shared_tmp_ax0 == batch_matmul_wmma_accumulator_b_c_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select1)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select1)
model.Add(B_shared_tmp_ax0 == batch_matmul_wmma_accumulator_b_c_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select2)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select2)
model.Add(B_shared_tmp_ax0 == batch_matmul_wmma_accumulator_b_c_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select3)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select3)
model.Add(sum([batch_matmul_wmma_accumulator_shared_pos_select0, batch_matmul_wmma_accumulator_shared_pos_select1, batch_matmul_wmma_accumulator_shared_pos_select2, batch_matmul_wmma_accumulator_shared_pos_select3]) == 1)
model.AddMultiplicationEquality(B_shared_ax0, [B_shared_tmp_ax0, batch_matmul_wmma_accumulator_sharedax0tileSpatial])
model.Add(B_shared_tmp_ax1 == batch_matmul_wmma_accumulator_j_c_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select0)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select0)
model.Add(B_shared_tmp_ax1 == batch_matmul_wmma_accumulator_j_c_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select1)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select1)
model.Add(B_shared_tmp_ax1 == batch_matmul_wmma_accumulator_j_c_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select2)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select2)
model.Add(B_shared_tmp_ax1 == batch_matmul_wmma_accumulator_j_c_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select3)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select3)
model.Add(sum([batch_matmul_wmma_accumulator_shared_pos_select0, batch_matmul_wmma_accumulator_shared_pos_select1, batch_matmul_wmma_accumulator_shared_pos_select2, batch_matmul_wmma_accumulator_shared_pos_select3]) == 1)
model.AddMultiplicationEquality(B_shared_ax1, [B_shared_tmp_ax1, batch_matmul_wmma_accumulator_sharedax2tileSpatial])
model.Add(B_shared_ax2 == batch_matmul_wmma_accumulator_k_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select0)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select0)
model.Add(B_shared_ax2 == batch_matmul_wmma_accumulator_k_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select1)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select1)
model.Add(B_shared_ax2 == batch_matmul_wmma_accumulator_k_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select2)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select2)
model.Add(B_shared_ax2 == batch_matmul_wmma_accumulator_k_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select3)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select3)
model.Add(sum([batch_matmul_wmma_accumulator_shared_pos_select0, batch_matmul_wmma_accumulator_shared_pos_select1, batch_matmul_wmma_accumulator_shared_pos_select2, batch_matmul_wmma_accumulator_shared_pos_select3]) == 1)
model.Add(B_shared_offset == 0).OnlyEnforceIf(B_shared_offset_cand0)
model.Add(B_shared_offset == 8).OnlyEnforceIf(B_shared_offset_cand1)
model.Add(B_shared_offset == 16).OnlyEnforceIf(B_shared_offset_cand2)
model.Add(B_shared_offset == 24).OnlyEnforceIf(B_shared_offset_cand3)
model.Add(B_shared_offset == 32).OnlyEnforceIf(B_shared_offset_cand4)
model.Add(B_shared_offset == 48).OnlyEnforceIf(B_shared_offset_cand5)
model.Add(sum([B_shared_offset_cand0, B_shared_offset_cand1, B_shared_offset_cand2, B_shared_offset_cand3, B_shared_offset_cand4, B_shared_offset_cand5]) == 1)
model.Add(sum([B_shared_ax2, B_shared_offset]) == B_shared_align_size)
model.AddMultiplicationEquality(B_shared_ax0_B_shared_ax1, [B_shared_ax0, B_shared_ax1])
model.AddMultiplicationEquality(B_shared_ax0_ax1_fused_ax2_fused, [B_shared_ax0_B_shared_ax1, B_shared_ax2])
model.Add(B_shared_vectorize == 1).OnlyEnforceIf(B_shared_vectorize_cand0)
model.Add(B_shared_vectorize == 2).OnlyEnforceIf(B_shared_vectorize_cand1)
model.Add(B_shared_vectorize == 4).OnlyEnforceIf(B_shared_vectorize_cand2)
model.Add(B_shared_vectorize == 8).OnlyEnforceIf(B_shared_vectorize_cand3)
model.Add(sum([B_shared_vectorize_cand0, B_shared_vectorize_cand1, B_shared_vectorize_cand2, B_shared_vectorize_cand3]) == 1)
model.Add(A_shared_wmma_matrix_a_ax0 == batch_matmul_wmma_accumulator_b_c_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select0)
model.Add(batch_matmul_wmma_accumulator_local_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select0)
model.Add(A_shared_wmma_matrix_a_ax0 == batch_matmul_wmma_accumulator_b_c_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select1)
model.Add(batch_matmul_wmma_accumulator_local_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select1)
model.Add(A_shared_wmma_matrix_a_ax0 == batch_matmul_wmma_accumulator_b_c_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select2)
model.Add(batch_matmul_wmma_accumulator_local_pos == 2).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select2)
model.Add(A_shared_wmma_matrix_a_ax0 == batch_matmul_wmma_accumulator_b_c_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select3)
model.Add(batch_matmul_wmma_accumulator_local_pos == 3).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select3)
model.Add(sum([batch_matmul_wmma_accumulator_local_pos_select0, batch_matmul_wmma_accumulator_local_pos_select1, batch_matmul_wmma_accumulator_local_pos_select2, batch_matmul_wmma_accumulator_local_pos_select3]) == 1)
model.Add(A_shared_wmma_matrix_a_ax1 == batch_matmul_wmma_accumulator_i_c_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select0)
model.Add(batch_matmul_wmma_accumulator_local_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select0)
model.Add(A_shared_wmma_matrix_a_ax1 == batch_matmul_wmma_accumulator_i_c_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select1)
model.Add(batch_matmul_wmma_accumulator_local_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select1)
model.Add(A_shared_wmma_matrix_a_ax1 == batch_matmul_wmma_accumulator_i_c_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select2)
model.Add(batch_matmul_wmma_accumulator_local_pos == 2).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select2)
model.Add(A_shared_wmma_matrix_a_ax1 == batch_matmul_wmma_accumulator_i_c_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select3)
model.Add(batch_matmul_wmma_accumulator_local_pos == 3).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select3)
model.Add(sum([batch_matmul_wmma_accumulator_local_pos_select0, batch_matmul_wmma_accumulator_local_pos_select1, batch_matmul_wmma_accumulator_local_pos_select2, batch_matmul_wmma_accumulator_local_pos_select3]) == 1)
model.Add(A_shared_wmma_matrix_a_ax2 == batch_matmul_wmma_accumulator_k_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select0)
model.Add(batch_matmul_wmma_accumulator_local_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select0)
model.Add(A_shared_wmma_matrix_a_ax2 == batch_matmul_wmma_accumulator_k_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select1)
model.Add(batch_matmul_wmma_accumulator_local_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select1)
model.Add(A_shared_wmma_matrix_a_ax2 == batch_matmul_wmma_accumulator_k_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select2)
model.Add(batch_matmul_wmma_accumulator_local_pos == 2).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select2)
model.Add(A_shared_wmma_matrix_a_ax2 == batch_matmul_wmma_accumulator_k_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select3)
model.Add(batch_matmul_wmma_accumulator_local_pos == 3).OnlyEnforceIf(batch_matmul_wmma_accumulator_local_pos_select3)
model.Add(sum([batch_matmul_wmma_accumulator_local_pos_select0, batch_matmul_wmma_accumulator_local_pos_select1, batch_matmul_wmma_accumulator_local_pos_select2, batch_matmul_wmma_accumulator_local_pos_select3]) == 1)
model.AddMultiplicationEquality(A_shared_wmma_matrix_a_ax0, [A_shared_wmma_matrix_a_ax0_outer, A_shared_wmma_matrix_a_ax0_inner])
model.Add(A_shared_wmma_matrix_a_ax0_inner == 1)
model.AddMultiplicationEquality(A_shared_wmma_matrix_a_ax1, [A_shared_wmma_matrix_a_ax1_outer, A_shared_wmma_matrix_a_ax1_inner])
model.Add(A_shared_wmma_matrix_a_ax1_inner == wmma_m)
model.AddMultiplicationEquality(A_shared_wmma_matrix_a_ax2, [A_shared_wmma_matrix_a_ax2_outer, A_shared_wmma_matrix_a_ax2_inner])
model.Add(A_shared_wmma_matrix_a_ax2_inner == wmma_k)
model.Add(A_shared_tmp_ax0 == batch_matmul_wmma_accumulator_b_c_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select0)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select0)
model.Add(A_shared_tmp_ax0 == batch_matmul_wmma_accumulator_b_c_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select1)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select1)
model.Add(A_shared_tmp_ax0 == batch_matmul_wmma_accumulator_b_c_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select2)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select2)
model.Add(A_shared_tmp_ax0 == batch_matmul_wmma_accumulator_b_c_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select3)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select3)
model.Add(sum([batch_matmul_wmma_accumulator_shared_pos_select0, batch_matmul_wmma_accumulator_shared_pos_select1, batch_matmul_wmma_accumulator_shared_pos_select2, batch_matmul_wmma_accumulator_shared_pos_select3]) == 1)
model.AddMultiplicationEquality(A_shared_ax0, [A_shared_tmp_ax0, batch_matmul_wmma_accumulator_sharedax0tileSpatial])
model.Add(A_shared_tmp_ax1 == batch_matmul_wmma_accumulator_i_c_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select0)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select0)
model.Add(A_shared_tmp_ax1 == batch_matmul_wmma_accumulator_i_c_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select1)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select1)
model.Add(A_shared_tmp_ax1 == batch_matmul_wmma_accumulator_i_c_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select2)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select2)
model.Add(A_shared_tmp_ax1 == batch_matmul_wmma_accumulator_i_c_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select3)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select3)
model.Add(sum([batch_matmul_wmma_accumulator_shared_pos_select0, batch_matmul_wmma_accumulator_shared_pos_select1, batch_matmul_wmma_accumulator_shared_pos_select2, batch_matmul_wmma_accumulator_shared_pos_select3]) == 1)
model.AddMultiplicationEquality(A_shared_ax1, [A_shared_tmp_ax1, batch_matmul_wmma_accumulator_sharedax1tileSpatial])
model.Add(A_shared_ax2 == batch_matmul_wmma_accumulator_k_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select0)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 0).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select0)
model.Add(A_shared_ax2 == batch_matmul_wmma_accumulator_k_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select1)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 1).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select1)
model.Add(A_shared_ax2 == batch_matmul_wmma_accumulator_k_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select2)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 2).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select2)
model.Add(A_shared_ax2 == batch_matmul_wmma_accumulator_k_inner_inner_inner_inner).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select3)
model.Add(batch_matmul_wmma_accumulator_shared_pos == 3).OnlyEnforceIf(batch_matmul_wmma_accumulator_shared_pos_select3)
model.Add(sum([batch_matmul_wmma_accumulator_shared_pos_select0, batch_matmul_wmma_accumulator_shared_pos_select1, batch_matmul_wmma_accumulator_shared_pos_select2, batch_matmul_wmma_accumulator_shared_pos_select3]) == 1)
model.Add(A_shared_offset == 0).OnlyEnforceIf(A_shared_offset_cand0)
model.Add(A_shared_offset == 8).OnlyEnforceIf(A_shared_offset_cand1)
model.Add(A_shared_offset == 16).OnlyEnforceIf(A_shared_offset_cand2)
model.Add(A_shared_offset == 24).OnlyEnforceIf(A_shared_offset_cand3)
model.Add(A_shared_offset == 32).OnlyEnforceIf(A_shared_offset_cand4)
model.Add(A_shared_offset == 48).OnlyEnforceIf(A_shared_offset_cand5)
model.Add(sum([A_shared_offset_cand0, A_shared_offset_cand1, A_shared_offset_cand2, A_shared_offset_cand3, A_shared_offset_cand4, A_shared_offset_cand5]) == 1)
model.Add(sum([A_shared_ax2, A_shared_offset]) == A_shared_align_size)
model.AddMultiplicationEquality(A_shared_ax0_A_shared_ax1, [A_shared_ax0, A_shared_ax1])
model.AddMultiplicationEquality(A_shared_ax0_ax1_fused_ax2_fused, [A_shared_ax0_A_shared_ax1, A_shared_ax2])
model.Add(A_shared_vectorize == 1).OnlyEnforceIf(A_shared_vectorize_cand0)
model.Add(A_shared_vectorize == 2).OnlyEnforceIf(A_shared_vectorize_cand1)
model.Add(A_shared_vectorize == 4).OnlyEnforceIf(A_shared_vectorize_cand2)
model.Add(A_shared_vectorize == 8).OnlyEnforceIf(A_shared_vectorize_cand3)
model.Add(sum([A_shared_vectorize_cand0, A_shared_vectorize_cand1, A_shared_vectorize_cand2, A_shared_vectorize_cand3]) == 1)
model.AddMultiplicationEquality(threads, [threadIdx_x, threadIdx_y])
model.AddMultiplicationEquality(A_shared_ax0_A_shared_ax1, [A_shared_ax0, A_shared_ax1])
model.AddMultiplicationEquality(A_shared_shared_mem_size, [A_shared_ax0_A_shared_ax1, A_shared_align_size])
model.AddMultiplicationEquality(B_shared_ax0_B_shared_ax1, [B_shared_ax0, B_shared_ax1])
model.AddMultiplicationEquality(B_shared_shared_mem_size, [B_shared_ax0_B_shared_ax1, B_shared_align_size])
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_shared_ax0_batch_matmul_wmma_accumulator_shared_ax1, [batch_matmul_wmma_accumulator_shared_ax0, batch_matmul_wmma_accumulator_shared_ax1])
model.AddMultiplicationEquality(batch_matmul_wmma_accumulator_shared_shared_mem_size, [batch_matmul_wmma_accumulator_shared_ax0_batch_matmul_wmma_accumulator_shared_ax1, batch_matmul_wmma_accumulator_shared_align_size])
solver = cp_model.CpSolver()
status = solver.Solve(model)
